// Code generated by go-swagger; DO NOT EDIT.

package organization_inventory

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPinInventoryOutputParams creates a new PinInventoryOutputParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPinInventoryOutputParams() *PinInventoryOutputParams {
	return &PinInventoryOutputParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPinInventoryOutputParamsWithTimeout creates a new PinInventoryOutputParams object
// with the ability to set a timeout on a request.
func NewPinInventoryOutputParamsWithTimeout(timeout time.Duration) *PinInventoryOutputParams {
	return &PinInventoryOutputParams{
		timeout: timeout,
	}
}

// NewPinInventoryOutputParamsWithContext creates a new PinInventoryOutputParams object
// with the ability to set a context for a request.
func NewPinInventoryOutputParamsWithContext(ctx context.Context) *PinInventoryOutputParams {
	return &PinInventoryOutputParams{
		Context: ctx,
	}
}

// NewPinInventoryOutputParamsWithHTTPClient creates a new PinInventoryOutputParams object
// with the ability to set a custom HTTPClient for a request.
func NewPinInventoryOutputParamsWithHTTPClient(client *http.Client) *PinInventoryOutputParams {
	return &PinInventoryOutputParams{
		HTTPClient: client,
	}
}

/*
PinInventoryOutputParams contains all the parameters to send to the API endpoint

	for the pin inventory output operation.

	Typically these are written to a http.Request.
*/
type PinInventoryOutputParams struct {

	/* InventoryOutputID.

	   ID of an inventory output (terraform state output)

	   Format: uint32
	*/
	InventoryOutputID uint32

	/* OrganizationCanonical.

	   A canonical of an organization.
	*/
	OrganizationCanonical string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the pin inventory output params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PinInventoryOutputParams) WithDefaults() *PinInventoryOutputParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the pin inventory output params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PinInventoryOutputParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the pin inventory output params
func (o *PinInventoryOutputParams) WithTimeout(timeout time.Duration) *PinInventoryOutputParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the pin inventory output params
func (o *PinInventoryOutputParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the pin inventory output params
func (o *PinInventoryOutputParams) WithContext(ctx context.Context) *PinInventoryOutputParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the pin inventory output params
func (o *PinInventoryOutputParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the pin inventory output params
func (o *PinInventoryOutputParams) WithHTTPClient(client *http.Client) *PinInventoryOutputParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the pin inventory output params
func (o *PinInventoryOutputParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInventoryOutputID adds the inventoryOutputID to the pin inventory output params
func (o *PinInventoryOutputParams) WithInventoryOutputID(inventoryOutputID uint32) *PinInventoryOutputParams {
	o.SetInventoryOutputID(inventoryOutputID)
	return o
}

// SetInventoryOutputID adds the inventoryOutputId to the pin inventory output params
func (o *PinInventoryOutputParams) SetInventoryOutputID(inventoryOutputID uint32) {
	o.InventoryOutputID = inventoryOutputID
}

// WithOrganizationCanonical adds the organizationCanonical to the pin inventory output params
func (o *PinInventoryOutputParams) WithOrganizationCanonical(organizationCanonical string) *PinInventoryOutputParams {
	o.SetOrganizationCanonical(organizationCanonical)
	return o
}

// SetOrganizationCanonical adds the organizationCanonical to the pin inventory output params
func (o *PinInventoryOutputParams) SetOrganizationCanonical(organizationCanonical string) {
	o.OrganizationCanonical = organizationCanonical
}

// WriteToRequest writes these params to a swagger request
func (o *PinInventoryOutputParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param inventory_output_id
	if err := r.SetPathParam("inventory_output_id", swag.FormatUint32(o.InventoryOutputID)); err != nil {
		return err
	}

	// path param organization_canonical
	if err := r.SetPathParam("organization_canonical", o.OrganizationCanonical); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
