# Changie docs
# https://changie.dev/config
#
# Advanced formatting/logic docs
# https://masterminds.github.io/sprig
changesDir: changelog/releases
unreleasedDir: ../unreleased
headerPath: ../header.tpl.md
versionHeaderPath: ""
versionFooterPath: ""
changelogPath: CHANGELOG.md
versionExt: md
componentFormat: "### {{.Component}}"
versionFormat: |
  ## [{{.Version}}] _{{.Time.Format "2006-01-02"}}_
headerFormat: |
  Cycloid CLI changelog:
kindFormat: "**{{.Kind}}**"
changeFormat: |
  - {{.Body}} ([CLI#{{.Custom.PR}}])
  {{if ne .Custom.DETAILS "" -}}
  *{{.Custom.DETAILS}}*
  {{- end -}}
footerFormat: |
  {{- range (customs .Changes "PR" | uniq) }}
  [CLI#{{.}}]: https://github.com/cycloidio/cycloid-cli/pull/{{.}}
  {{- end}}
components:
  - API Keys
  - Authentication
  - Budget
  - CLI
  - Cloud Cost Management
  - Concourse
  - Config Repo
  - Credentials
  - Dashboard
  - Environments
  - Events
  - InfraImport
  - InfraPolicies
  - InfraView
  - Inventory
  - Invitations
  - KPI
  - Licence
  - Logs
  - Members
  - Monitoring
  - MSP
  - Notifications
  - Organizations
  - Pipeline Designer
  - Pipeline view
  - Pipelines Overview
  - Profile-User-SalesForce
  - Project
  - Quota
  - Roles
  - Service Catalog
  - StackCraft
  - StackForms
  - Start&Stop Env
  - Status Page
  - Teams
  - TerraCost
  - Workers
  - Other

kinds:
  - label: ADDED
  - label: BREAKING
  - label: CHANGED
  - label: DEPRECATED
  - label: FIXED
  - label: INTERNAL
  - label: REMOVED
  - label: SECURITY

# --[Notes]--
#
# :: key & label ::
# Doesn't print out both key and label in the cmd line
# so you'll need to prepend the label with the key.
#
# :: optional ::
# Contrary to the docs, int is not optional. So if you
# want to make something optional, you need string.
#
# :: order ::
# We cannot dictate the order for custom properties,
# it's also not clear what logic is used to order them.
#
# :: DETAILS ::
# If your command line goes funky after typing then just
# press enter and finish writing in your IDE instead.
custom:
  - key: TYPE
    type: enum
    enumOptions:
      - CLI
  - key: PR
    type: int
    minInt: 1
  - key: DETAILS
    label: DETAILS - for public release, should be approx 1-2 sentences (user impact), optional.
    type: string
