version: "2"
run:
  concurrency: 4
  go: "1.24"
linters:
  default: none
  enable:
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused
  settings:
    misspell:
      locale: US
      ignore-rules:
        - licence
        - licences
        - utilisation
        - cancelled
    staticcheck:
      checks:
        - -SA1019
        - -SA5012
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
