// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cycloidio/youdeploy-cli/client/models"
)

// NewPasswordResetReqParams creates a new PasswordResetReqParams object
// with the default values initialized.
func NewPasswordResetReqParams() *PasswordResetReqParams {
	var ()
	return &PasswordResetReqParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPasswordResetReqParamsWithTimeout creates a new PasswordResetReqParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPasswordResetReqParamsWithTimeout(timeout time.Duration) *PasswordResetReqParams {
	var ()
	return &PasswordResetReqParams{

		timeout: timeout,
	}
}

// NewPasswordResetReqParamsWithContext creates a new PasswordResetReqParams object
// with the default values initialized, and the ability to set a context for a request
func NewPasswordResetReqParamsWithContext(ctx context.Context) *PasswordResetReqParams {
	var ()
	return &PasswordResetReqParams{

		Context: ctx,
	}
}

// NewPasswordResetReqParamsWithHTTPClient creates a new PasswordResetReqParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPasswordResetReqParamsWithHTTPClient(client *http.Client) *PasswordResetReqParams {
	var ()
	return &PasswordResetReqParams{
		HTTPClient: client,
	}
}

/*PasswordResetReqParams contains all the parameters to send to the API endpoint
for the password reset req operation typically these are written to a http.Request
*/
type PasswordResetReqParams struct {

	/*Body
	  The reset password payload

	*/
	Body *models.UserPasswordResetReq

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the password reset req params
func (o *PasswordResetReqParams) WithTimeout(timeout time.Duration) *PasswordResetReqParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the password reset req params
func (o *PasswordResetReqParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the password reset req params
func (o *PasswordResetReqParams) WithContext(ctx context.Context) *PasswordResetReqParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the password reset req params
func (o *PasswordResetReqParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the password reset req params
func (o *PasswordResetReqParams) WithHTTPClient(client *http.Client) *PasswordResetReqParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the password reset req params
func (o *PasswordResetReqParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the password reset req params
func (o *PasswordResetReqParams) WithBody(body *models.UserPasswordResetReq) *PasswordResetReqParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the password reset req params
func (o *PasswordResetReqParams) SetBody(body *models.UserPasswordResetReq) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PasswordResetReqParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
