// Code generated by go-swagger; DO NOT EDIT.

package organization_pipelines_jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUnpauseJobParams creates a new UnpauseJobParams object
// with the default values initialized.
func NewUnpauseJobParams() *UnpauseJobParams {
	var ()
	return &UnpauseJobParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUnpauseJobParamsWithTimeout creates a new UnpauseJobParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUnpauseJobParamsWithTimeout(timeout time.Duration) *UnpauseJobParams {
	var ()
	return &UnpauseJobParams{

		timeout: timeout,
	}
}

// NewUnpauseJobParamsWithContext creates a new UnpauseJobParams object
// with the default values initialized, and the ability to set a context for a request
func NewUnpauseJobParamsWithContext(ctx context.Context) *UnpauseJobParams {
	var ()
	return &UnpauseJobParams{

		Context: ctx,
	}
}

// NewUnpauseJobParamsWithHTTPClient creates a new UnpauseJobParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUnpauseJobParamsWithHTTPClient(client *http.Client) *UnpauseJobParams {
	var ()
	return &UnpauseJobParams{
		HTTPClient: client,
	}
}

/*UnpauseJobParams contains all the parameters to send to the API endpoint
for the unpause job operation typically these are written to a http.Request
*/
type UnpauseJobParams struct {

	/*InpathPipelineName
	  A pipeline name

	*/
	InpathPipelineName string
	/*JobName
	  A job name

	*/
	JobName string
	/*OrganizationCanonical
	  A canonical of an organization.

	*/
	OrganizationCanonical string
	/*ProjectCanonical
	  A canonical of a project.

	*/
	ProjectCanonical string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the unpause job params
func (o *UnpauseJobParams) WithTimeout(timeout time.Duration) *UnpauseJobParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the unpause job params
func (o *UnpauseJobParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the unpause job params
func (o *UnpauseJobParams) WithContext(ctx context.Context) *UnpauseJobParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the unpause job params
func (o *UnpauseJobParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the unpause job params
func (o *UnpauseJobParams) WithHTTPClient(client *http.Client) *UnpauseJobParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the unpause job params
func (o *UnpauseJobParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInpathPipelineName adds the inpathPipelineName to the unpause job params
func (o *UnpauseJobParams) WithInpathPipelineName(inpathPipelineName string) *UnpauseJobParams {
	o.SetInpathPipelineName(inpathPipelineName)
	return o
}

// SetInpathPipelineName adds the inpathPipelineName to the unpause job params
func (o *UnpauseJobParams) SetInpathPipelineName(inpathPipelineName string) {
	o.InpathPipelineName = inpathPipelineName
}

// WithJobName adds the jobName to the unpause job params
func (o *UnpauseJobParams) WithJobName(jobName string) *UnpauseJobParams {
	o.SetJobName(jobName)
	return o
}

// SetJobName adds the jobName to the unpause job params
func (o *UnpauseJobParams) SetJobName(jobName string) {
	o.JobName = jobName
}

// WithOrganizationCanonical adds the organizationCanonical to the unpause job params
func (o *UnpauseJobParams) WithOrganizationCanonical(organizationCanonical string) *UnpauseJobParams {
	o.SetOrganizationCanonical(organizationCanonical)
	return o
}

// SetOrganizationCanonical adds the organizationCanonical to the unpause job params
func (o *UnpauseJobParams) SetOrganizationCanonical(organizationCanonical string) {
	o.OrganizationCanonical = organizationCanonical
}

// WithProjectCanonical adds the projectCanonical to the unpause job params
func (o *UnpauseJobParams) WithProjectCanonical(projectCanonical string) *UnpauseJobParams {
	o.SetProjectCanonical(projectCanonical)
	return o
}

// SetProjectCanonical adds the projectCanonical to the unpause job params
func (o *UnpauseJobParams) SetProjectCanonical(projectCanonical string) {
	o.ProjectCanonical = projectCanonical
}

// WriteToRequest writes these params to a swagger request
func (o *UnpauseJobParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param inpath_pipeline_name
	if err := r.SetPathParam("inpath_pipeline_name", o.InpathPipelineName); err != nil {
		return err
	}

	// path param job_name
	if err := r.SetPathParam("job_name", o.JobName); err != nil {
		return err
	}

	// path param organization_canonical
	if err := r.SetPathParam("organization_canonical", o.OrganizationCanonical); err != nil {
		return err
	}

	// path param project_canonical
	if err := r.SetPathParam("project_canonical", o.ProjectCanonical); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
