services:
  ## An email server which doesn't supports TLS but it supports authentication
  email-smtp-no-tls-auth:
    container_name: smtp
    image: mailhog/mailhog:v1.0.0
    command: -auth-file /mailhog.auth
    configs: [mailhog.auth]
    attach: false
    restart: always
    networks:
      tf-tests:
        ipv4_address: "${SUBNET_CIDR:-192.100.100}.6"

