// Code generated by go-swagger; DO NOT EDIT.

package organization_children

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetChildrenParams creates a new GetChildrenParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetChildrenParams() *GetChildrenParams {
	return &GetChildrenParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetChildrenParamsWithTimeout creates a new GetChildrenParams object
// with the ability to set a timeout on a request.
func NewGetChildrenParamsWithTimeout(timeout time.Duration) *GetChildrenParams {
	return &GetChildrenParams{
		timeout: timeout,
	}
}

// NewGetChildrenParamsWithContext creates a new GetChildrenParams object
// with the ability to set a context for a request.
func NewGetChildrenParamsWithContext(ctx context.Context) *GetChildrenParams {
	return &GetChildrenParams{
		Context: ctx,
	}
}

// NewGetChildrenParamsWithHTTPClient creates a new GetChildrenParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetChildrenParamsWithHTTPClient(client *http.Client) *GetChildrenParams {
	return &GetChildrenParams{
		HTTPClient: client,
	}
}

/*
GetChildrenParams contains all the parameters to send to the API endpoint

	for the get children operation.

	Typically these are written to a http.Request.
*/
type GetChildrenParams struct {

	/* OrderBy.

	   Allows to order the list of items. Example usage: field_name:asc

	*/
	OrderBy *string

	/* OrganizationCanonical.

	   A canonical of an organization.
	*/
	OrganizationCanonical string

	/* OrganizationCreatedAt.

	   Search by organization's creation date

	   Format: date-time
	*/
	OrganizationCreatedAt *strfmt.DateTime

	/* OrganizationName.

	   Search by the organization's name
	*/
	OrganizationName *string

	/* PageIndex.

	   The page number to request. The first page is 1.

	   Format: uint32
	   Default: 1
	*/
	PageIndex *uint32

	/* PageSize.

	   The number of items at most which the response can have.

	   Format: uint32
	   Default: 1000
	*/
	PageSize *uint32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get children params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetChildrenParams) WithDefaults() *GetChildrenParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get children params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetChildrenParams) SetDefaults() {
	var (
		pageIndexDefault = uint32(1)

		pageSizeDefault = uint32(1000)
	)

	val := GetChildrenParams{
		PageIndex: &pageIndexDefault,
		PageSize:  &pageSizeDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get children params
func (o *GetChildrenParams) WithTimeout(timeout time.Duration) *GetChildrenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get children params
func (o *GetChildrenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get children params
func (o *GetChildrenParams) WithContext(ctx context.Context) *GetChildrenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get children params
func (o *GetChildrenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get children params
func (o *GetChildrenParams) WithHTTPClient(client *http.Client) *GetChildrenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get children params
func (o *GetChildrenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrderBy adds the orderBy to the get children params
func (o *GetChildrenParams) WithOrderBy(orderBy *string) *GetChildrenParams {
	o.SetOrderBy(orderBy)
	return o
}

// SetOrderBy adds the orderBy to the get children params
func (o *GetChildrenParams) SetOrderBy(orderBy *string) {
	o.OrderBy = orderBy
}

// WithOrganizationCanonical adds the organizationCanonical to the get children params
func (o *GetChildrenParams) WithOrganizationCanonical(organizationCanonical string) *GetChildrenParams {
	o.SetOrganizationCanonical(organizationCanonical)
	return o
}

// SetOrganizationCanonical adds the organizationCanonical to the get children params
func (o *GetChildrenParams) SetOrganizationCanonical(organizationCanonical string) {
	o.OrganizationCanonical = organizationCanonical
}

// WithOrganizationCreatedAt adds the organizationCreatedAt to the get children params
func (o *GetChildrenParams) WithOrganizationCreatedAt(organizationCreatedAt *strfmt.DateTime) *GetChildrenParams {
	o.SetOrganizationCreatedAt(organizationCreatedAt)
	return o
}

// SetOrganizationCreatedAt adds the organizationCreatedAt to the get children params
func (o *GetChildrenParams) SetOrganizationCreatedAt(organizationCreatedAt *strfmt.DateTime) {
	o.OrganizationCreatedAt = organizationCreatedAt
}

// WithOrganizationName adds the organizationName to the get children params
func (o *GetChildrenParams) WithOrganizationName(organizationName *string) *GetChildrenParams {
	o.SetOrganizationName(organizationName)
	return o
}

// SetOrganizationName adds the organizationName to the get children params
func (o *GetChildrenParams) SetOrganizationName(organizationName *string) {
	o.OrganizationName = organizationName
}

// WithPageIndex adds the pageIndex to the get children params
func (o *GetChildrenParams) WithPageIndex(pageIndex *uint32) *GetChildrenParams {
	o.SetPageIndex(pageIndex)
	return o
}

// SetPageIndex adds the pageIndex to the get children params
func (o *GetChildrenParams) SetPageIndex(pageIndex *uint32) {
	o.PageIndex = pageIndex
}

// WithPageSize adds the pageSize to the get children params
func (o *GetChildrenParams) WithPageSize(pageSize *uint32) *GetChildrenParams {
	o.SetPageSize(pageSize)
	return o
}

// SetPageSize adds the pageSize to the get children params
func (o *GetChildrenParams) SetPageSize(pageSize *uint32) {
	o.PageSize = pageSize
}

// WriteToRequest writes these params to a swagger request
func (o *GetChildrenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.OrderBy != nil {

		// query param order_by
		var qrOrderBy string

		if o.OrderBy != nil {
			qrOrderBy = *o.OrderBy
		}
		qOrderBy := qrOrderBy
		if qOrderBy != "" {

			if err := r.SetQueryParam("order_by", qOrderBy); err != nil {
				return err
			}
		}
	}

	// path param organization_canonical
	if err := r.SetPathParam("organization_canonical", o.OrganizationCanonical); err != nil {
		return err
	}

	if o.OrganizationCreatedAt != nil {

		// query param organization_created_at
		var qrOrganizationCreatedAt strfmt.DateTime

		if o.OrganizationCreatedAt != nil {
			qrOrganizationCreatedAt = *o.OrganizationCreatedAt
		}
		qOrganizationCreatedAt := qrOrganizationCreatedAt.String()
		if qOrganizationCreatedAt != "" {

			if err := r.SetQueryParam("organization_created_at", qOrganizationCreatedAt); err != nil {
				return err
			}
		}
	}

	if o.OrganizationName != nil {

		// query param organization_name
		var qrOrganizationName string

		if o.OrganizationName != nil {
			qrOrganizationName = *o.OrganizationName
		}
		qOrganizationName := qrOrganizationName
		if qOrganizationName != "" {

			if err := r.SetQueryParam("organization_name", qOrganizationName); err != nil {
				return err
			}
		}
	}

	if o.PageIndex != nil {

		// query param page_index
		var qrPageIndex uint32

		if o.PageIndex != nil {
			qrPageIndex = *o.PageIndex
		}
		qPageIndex := swag.FormatUint32(qrPageIndex)
		if qPageIndex != "" {

			if err := r.SetQueryParam("page_index", qPageIndex); err != nil {
				return err
			}
		}
	}

	if o.PageSize != nil {

		// query param page_size
		var qrPageSize uint32

		if o.PageSize != nil {
			qrPageSize = *o.PageSize
		}
		qPageSize := swag.FormatUint32(qrPageSize)
		if qPageSize != "" {

			if err := r.SetQueryParam("page_size", qPageSize); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
