// Code generated by go-swagger; DO NOT EDIT.

package organization_infrastructure

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/cycloidio/cycloid-cli/client/models"
)

// GetRunningInfraAWSBucketsReader is a Reader for the GetRunningInfraAWSBuckets structure.
type GetRunningInfraAWSBucketsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRunningInfraAWSBucketsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetRunningInfraAWSBucketsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetRunningInfraAWSBucketsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetRunningInfraAWSBucketsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewGetRunningInfraAWSBucketsUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewGetRunningInfraAWSBucketsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetRunningInfraAWSBucketsOK creates a GetRunningInfraAWSBucketsOK with default headers values
func NewGetRunningInfraAWSBucketsOK() *GetRunningInfraAWSBucketsOK {
	return &GetRunningInfraAWSBucketsOK{}
}

/*
GetRunningInfraAWSBucketsOK describes a response with status code 200, with default header values.

The list of AWS S3 buckets which matches the scope specified by the filter.
*/
type GetRunningInfraAWSBucketsOK struct {
	Payload *GetRunningInfraAWSBucketsOKBody
}

// IsSuccess returns true when this get running infra a w s buckets o k response has a 2xx status code
func (o *GetRunningInfraAWSBucketsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get running infra a w s buckets o k response has a 3xx status code
func (o *GetRunningInfraAWSBucketsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get running infra a w s buckets o k response has a 4xx status code
func (o *GetRunningInfraAWSBucketsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get running infra a w s buckets o k response has a 5xx status code
func (o *GetRunningInfraAWSBucketsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get running infra a w s buckets o k response a status code equal to that given
func (o *GetRunningInfraAWSBucketsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get running infra a w s buckets o k response
func (o *GetRunningInfraAWSBucketsOK) Code() int {
	return 200
}

func (o *GetRunningInfraAWSBucketsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/infrastructures/aws/buckets][%d] getRunningInfraAWSBucketsOK %s", 200, payload)
}

func (o *GetRunningInfraAWSBucketsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/infrastructures/aws/buckets][%d] getRunningInfraAWSBucketsOK %s", 200, payload)
}

func (o *GetRunningInfraAWSBucketsOK) GetPayload() *GetRunningInfraAWSBucketsOKBody {
	return o.Payload
}

func (o *GetRunningInfraAWSBucketsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetRunningInfraAWSBucketsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRunningInfraAWSBucketsForbidden creates a GetRunningInfraAWSBucketsForbidden with default headers values
func NewGetRunningInfraAWSBucketsForbidden() *GetRunningInfraAWSBucketsForbidden {
	return &GetRunningInfraAWSBucketsForbidden{}
}

/*
GetRunningInfraAWSBucketsForbidden describes a response with status code 403, with default header values.

The authenticated user cannot perform the operation because, it doesn't have permissions for such operation.
*/
type GetRunningInfraAWSBucketsForbidden struct {

	/* The length of the response body in octets (8-bit bytes).

	   Format: uint64
	*/
	ContentLength uint64

	Payload *models.ErrorPayload
}

// IsSuccess returns true when this get running infra a w s buckets forbidden response has a 2xx status code
func (o *GetRunningInfraAWSBucketsForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get running infra a w s buckets forbidden response has a 3xx status code
func (o *GetRunningInfraAWSBucketsForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get running infra a w s buckets forbidden response has a 4xx status code
func (o *GetRunningInfraAWSBucketsForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get running infra a w s buckets forbidden response has a 5xx status code
func (o *GetRunningInfraAWSBucketsForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get running infra a w s buckets forbidden response a status code equal to that given
func (o *GetRunningInfraAWSBucketsForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get running infra a w s buckets forbidden response
func (o *GetRunningInfraAWSBucketsForbidden) Code() int {
	return 403
}

func (o *GetRunningInfraAWSBucketsForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/infrastructures/aws/buckets][%d] getRunningInfraAWSBucketsForbidden %s", 403, payload)
}

func (o *GetRunningInfraAWSBucketsForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/infrastructures/aws/buckets][%d] getRunningInfraAWSBucketsForbidden %s", 403, payload)
}

func (o *GetRunningInfraAWSBucketsForbidden) GetPayload() *models.ErrorPayload {
	return o.Payload
}

func (o *GetRunningInfraAWSBucketsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Content-Length
	hdrContentLength := response.GetHeader("Content-Length")

	if hdrContentLength != "" {
		valcontentLength, err := swag.ConvertUint64(hdrContentLength)
		if err != nil {
			return errors.InvalidType("Content-Length", "header", "uint64", hdrContentLength)
		}
		o.ContentLength = valcontentLength
	}

	o.Payload = new(models.ErrorPayload)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRunningInfraAWSBucketsNotFound creates a GetRunningInfraAWSBucketsNotFound with default headers values
func NewGetRunningInfraAWSBucketsNotFound() *GetRunningInfraAWSBucketsNotFound {
	return &GetRunningInfraAWSBucketsNotFound{}
}

/*
GetRunningInfraAWSBucketsNotFound describes a response with status code 404, with default header values.

The response sent when any of the entities present in the path is not found.
*/
type GetRunningInfraAWSBucketsNotFound struct {

	/* The length of the response body in octets (8-bit bytes).

	   Format: uint64
	*/
	ContentLength uint64

	Payload *models.ErrorPayload
}

// IsSuccess returns true when this get running infra a w s buckets not found response has a 2xx status code
func (o *GetRunningInfraAWSBucketsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get running infra a w s buckets not found response has a 3xx status code
func (o *GetRunningInfraAWSBucketsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get running infra a w s buckets not found response has a 4xx status code
func (o *GetRunningInfraAWSBucketsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get running infra a w s buckets not found response has a 5xx status code
func (o *GetRunningInfraAWSBucketsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get running infra a w s buckets not found response a status code equal to that given
func (o *GetRunningInfraAWSBucketsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get running infra a w s buckets not found response
func (o *GetRunningInfraAWSBucketsNotFound) Code() int {
	return 404
}

func (o *GetRunningInfraAWSBucketsNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/infrastructures/aws/buckets][%d] getRunningInfraAWSBucketsNotFound %s", 404, payload)
}

func (o *GetRunningInfraAWSBucketsNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/infrastructures/aws/buckets][%d] getRunningInfraAWSBucketsNotFound %s", 404, payload)
}

func (o *GetRunningInfraAWSBucketsNotFound) GetPayload() *models.ErrorPayload {
	return o.Payload
}

func (o *GetRunningInfraAWSBucketsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Content-Length
	hdrContentLength := response.GetHeader("Content-Length")

	if hdrContentLength != "" {
		valcontentLength, err := swag.ConvertUint64(hdrContentLength)
		if err != nil {
			return errors.InvalidType("Content-Length", "header", "uint64", hdrContentLength)
		}
		o.ContentLength = valcontentLength
	}

	o.Payload = new(models.ErrorPayload)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRunningInfraAWSBucketsUnprocessableEntity creates a GetRunningInfraAWSBucketsUnprocessableEntity with default headers values
func NewGetRunningInfraAWSBucketsUnprocessableEntity() *GetRunningInfraAWSBucketsUnprocessableEntity {
	return &GetRunningInfraAWSBucketsUnprocessableEntity{}
}

/*
GetRunningInfraAWSBucketsUnprocessableEntity describes a response with status code 422, with default header values.

All the custom errors that are generated from the Cycloid API
*/
type GetRunningInfraAWSBucketsUnprocessableEntity struct {

	/* The length of the response body in octets (8-bit bytes).

	   Format: uint64
	*/
	ContentLength uint64

	Payload *models.ErrorPayload
}

// IsSuccess returns true when this get running infra a w s buckets unprocessable entity response has a 2xx status code
func (o *GetRunningInfraAWSBucketsUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get running infra a w s buckets unprocessable entity response has a 3xx status code
func (o *GetRunningInfraAWSBucketsUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get running infra a w s buckets unprocessable entity response has a 4xx status code
func (o *GetRunningInfraAWSBucketsUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this get running infra a w s buckets unprocessable entity response has a 5xx status code
func (o *GetRunningInfraAWSBucketsUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this get running infra a w s buckets unprocessable entity response a status code equal to that given
func (o *GetRunningInfraAWSBucketsUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the get running infra a w s buckets unprocessable entity response
func (o *GetRunningInfraAWSBucketsUnprocessableEntity) Code() int {
	return 422
}

func (o *GetRunningInfraAWSBucketsUnprocessableEntity) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/infrastructures/aws/buckets][%d] getRunningInfraAWSBucketsUnprocessableEntity %s", 422, payload)
}

func (o *GetRunningInfraAWSBucketsUnprocessableEntity) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/infrastructures/aws/buckets][%d] getRunningInfraAWSBucketsUnprocessableEntity %s", 422, payload)
}

func (o *GetRunningInfraAWSBucketsUnprocessableEntity) GetPayload() *models.ErrorPayload {
	return o.Payload
}

func (o *GetRunningInfraAWSBucketsUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Content-Length
	hdrContentLength := response.GetHeader("Content-Length")

	if hdrContentLength != "" {
		valcontentLength, err := swag.ConvertUint64(hdrContentLength)
		if err != nil {
			return errors.InvalidType("Content-Length", "header", "uint64", hdrContentLength)
		}
		o.ContentLength = valcontentLength
	}

	o.Payload = new(models.ErrorPayload)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRunningInfraAWSBucketsDefault creates a GetRunningInfraAWSBucketsDefault with default headers values
func NewGetRunningInfraAWSBucketsDefault(code int) *GetRunningInfraAWSBucketsDefault {
	return &GetRunningInfraAWSBucketsDefault{
		_statusCode: code,
	}
}

/*
GetRunningInfraAWSBucketsDefault describes a response with status code -1, with default header values.

The response sent when an unexpected error happened, as known as an internal server error.
*/
type GetRunningInfraAWSBucketsDefault struct {
	_statusCode int

	/* The length of the response body in octets (8-bit bytes).

	   Format: uint64
	*/
	ContentLength uint64

	Payload *models.ErrorPayload
}

// IsSuccess returns true when this get running infra a w s buckets default response has a 2xx status code
func (o *GetRunningInfraAWSBucketsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get running infra a w s buckets default response has a 3xx status code
func (o *GetRunningInfraAWSBucketsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get running infra a w s buckets default response has a 4xx status code
func (o *GetRunningInfraAWSBucketsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get running infra a w s buckets default response has a 5xx status code
func (o *GetRunningInfraAWSBucketsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get running infra a w s buckets default response a status code equal to that given
func (o *GetRunningInfraAWSBucketsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get running infra a w s buckets default response
func (o *GetRunningInfraAWSBucketsDefault) Code() int {
	return o._statusCode
}

func (o *GetRunningInfraAWSBucketsDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/infrastructures/aws/buckets][%d] getRunningInfraAWSBuckets default %s", o._statusCode, payload)
}

func (o *GetRunningInfraAWSBucketsDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/infrastructures/aws/buckets][%d] getRunningInfraAWSBuckets default %s", o._statusCode, payload)
}

func (o *GetRunningInfraAWSBucketsDefault) GetPayload() *models.ErrorPayload {
	return o.Payload
}

func (o *GetRunningInfraAWSBucketsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Content-Length
	hdrContentLength := response.GetHeader("Content-Length")

	if hdrContentLength != "" {
		valcontentLength, err := swag.ConvertUint64(hdrContentLength)
		if err != nil {
			return errors.InvalidType("Content-Length", "header", "uint64", hdrContentLength)
		}
		o.ContentLength = valcontentLength
	}

	o.Payload = new(models.ErrorPayload)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
GetRunningInfraAWSBucketsOKBody Although this response contains a collection of items, it doesn't have pagination because the AWS SDK, to request the S3 Buckets resources, doesn't provide any pagination mechanism.
swagger:model GetRunningInfraAWSBucketsOKBody
*/
type GetRunningInfraAWSBucketsOKBody struct {

	// data
	// Required: true
	Data []models.AWSInfrastructureResourceBucket `json:"data"`
}

// Validate validates this get running infra a w s buckets o k body
func (o *GetRunningInfraAWSBucketsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetRunningInfraAWSBucketsOKBody) validateData(formats strfmt.Registry) error {

	if err := validate.Required("getRunningInfraAWSBucketsOK"+"."+"data", "body", o.Data); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get running infra a w s buckets o k body based on context it is used
func (o *GetRunningInfraAWSBucketsOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetRunningInfraAWSBucketsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetRunningInfraAWSBucketsOKBody) UnmarshalBinary(b []byte) error {
	var res GetRunningInfraAWSBucketsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
