// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Appearance Appearance
//
// An Appearance holds the values of the branding configuration, which are rendered across an organization
// swagger:model Appearance
type Appearance struct {

	// canonical
	// Required: true
	// Max Length: 100
	// Min Length: 1
	// Pattern: ^[a-z0-9]+[a-z0-9\-_]+[a-z0-9]+$
	Canonical *string `json:"canonical"`

	// color
	// Required: true
	Color *AppearanceColor `json:"color"`

	// created at
	// Minimum: 0
	CreatedAt *uint64 `json:"created_at,omitempty"`

	// display name
	// Required: true
	// Max Length: 50
	// Min Length: 1
	DisplayName *string `json:"display_name"`

	// favicon
	// Required: true
	// Format: uri
	Favicon *strfmt.URI `json:"favicon"`

	// footer
	// Required: true
	// Max Length: 50
	// Min Length: 0
	Footer *string `json:"footer"`

	// is active
	IsActive bool `json:"is_active,omitempty"`

	// logo
	// Required: true
	// Format: uri
	Logo *strfmt.URI `json:"logo"`

	// name
	// Required: true
	// Max Length: 50
	// Min Length: 1
	Name *string `json:"name"`

	// updated at
	// Minimum: 0
	UpdatedAt *uint64 `json:"updated_at,omitempty"`
}

// Validate validates this appearance
func (m *Appearance) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCanonical(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateColor(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDisplayName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFavicon(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFooter(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLogo(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdatedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Appearance) validateCanonical(formats strfmt.Registry) error {

	if err := validate.Required("canonical", "body", m.Canonical); err != nil {
		return err
	}

	if err := validate.MinLength("canonical", "body", string(*m.Canonical), 1); err != nil {
		return err
	}

	if err := validate.MaxLength("canonical", "body", string(*m.Canonical), 100); err != nil {
		return err
	}

	if err := validate.Pattern("canonical", "body", string(*m.Canonical), `^[a-z0-9]+[a-z0-9\-_]+[a-z0-9]+$`); err != nil {
		return err
	}

	return nil
}

func (m *Appearance) validateColor(formats strfmt.Registry) error {

	if err := validate.Required("color", "body", m.Color); err != nil {
		return err
	}

	if m.Color != nil {
		if err := m.Color.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("color")
			}
			return err
		}
	}

	return nil
}

func (m *Appearance) validateCreatedAt(formats strfmt.Registry) error {

	if swag.IsZero(m.CreatedAt) { // not required
		return nil
	}

	if err := validate.MinimumInt("created_at", "body", int64(*m.CreatedAt), 0, false); err != nil {
		return err
	}

	return nil
}

func (m *Appearance) validateDisplayName(formats strfmt.Registry) error {

	if err := validate.Required("display_name", "body", m.DisplayName); err != nil {
		return err
	}

	if err := validate.MinLength("display_name", "body", string(*m.DisplayName), 1); err != nil {
		return err
	}

	if err := validate.MaxLength("display_name", "body", string(*m.DisplayName), 50); err != nil {
		return err
	}

	return nil
}

func (m *Appearance) validateFavicon(formats strfmt.Registry) error {

	if err := validate.Required("favicon", "body", m.Favicon); err != nil {
		return err
	}

	if err := validate.FormatOf("favicon", "body", "uri", m.Favicon.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Appearance) validateFooter(formats strfmt.Registry) error {

	if err := validate.Required("footer", "body", m.Footer); err != nil {
		return err
	}

	if err := validate.MinLength("footer", "body", string(*m.Footer), 0); err != nil {
		return err
	}

	if err := validate.MaxLength("footer", "body", string(*m.Footer), 50); err != nil {
		return err
	}

	return nil
}

func (m *Appearance) validateLogo(formats strfmt.Registry) error {

	if err := validate.Required("logo", "body", m.Logo); err != nil {
		return err
	}

	if err := validate.FormatOf("logo", "body", "uri", m.Logo.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Appearance) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	if err := validate.MinLength("name", "body", string(*m.Name), 1); err != nil {
		return err
	}

	if err := validate.MaxLength("name", "body", string(*m.Name), 50); err != nil {
		return err
	}

	return nil
}

func (m *Appearance) validateUpdatedAt(formats strfmt.Registry) error {

	if swag.IsZero(m.UpdatedAt) { // not required
		return nil
	}

	if err := validate.MinimumInt("updated_at", "body", int64(*m.UpdatedAt), 0, false); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Appearance) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Appearance) UnmarshalBinary(b []byte) error {
	var res Appearance
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// AppearanceColor appearance color
// swagger:model AppearanceColor
type AppearanceColor struct {

	// Blue color value of the RGB color
	// Required: true
	// Maximum: 255
	// Minimum: 0
	B *uint32 `json:"b"`

	// Green color value of the RGB color
	// Required: true
	// Maximum: 255
	// Minimum: 0
	G *uint32 `json:"g"`

	// Red color value of the RGB color
	// Required: true
	// Maximum: 255
	// Minimum: 0
	R *uint32 `json:"r"`
}

// Validate validates this appearance color
func (m *AppearanceColor) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateB(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateG(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateR(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AppearanceColor) validateB(formats strfmt.Registry) error {

	if err := validate.Required("color"+"."+"b", "body", m.B); err != nil {
		return err
	}

	if err := validate.MinimumInt("color"+"."+"b", "body", int64(*m.B), 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("color"+"."+"b", "body", int64(*m.B), 255, false); err != nil {
		return err
	}

	return nil
}

func (m *AppearanceColor) validateG(formats strfmt.Registry) error {

	if err := validate.Required("color"+"."+"g", "body", m.G); err != nil {
		return err
	}

	if err := validate.MinimumInt("color"+"."+"g", "body", int64(*m.G), 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("color"+"."+"g", "body", int64(*m.G), 255, false); err != nil {
		return err
	}

	return nil
}

func (m *AppearanceColor) validateR(formats strfmt.Registry) error {

	if err := validate.Required("color"+"."+"r", "body", m.R); err != nil {
		return err
	}

	if err := validate.MinimumInt("color"+"."+"r", "body", int64(*m.R), 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("color"+"."+"r", "body", int64(*m.R), 255, false); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AppearanceColor) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AppearanceColor) UnmarshalBinary(b []byte) error {
	var res AppearanceColor
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
