// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateCredential Credential
//
// Represents the Credential
// swagger:model CreateCredential
type CreateCredential struct {

	// canonical
	// Max Length: 30
	// Min Length: 3
	// Pattern: ^[a-z0-9]+[a-z0-9\-_]+[a-z0-9]+$
	Canonical string `json:"canonical,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// name
	// Required: true
	Name *string `json:"name"`

	// User canonical that owns this credential. If omitted then the person creating this
	// credential will be assigned as owner. When a user is the owner of a credential he has
	// all the permissions on it.
	//
	Owner string `json:"owner,omitempty"`

	// path
	// Required: true
	// Pattern: [a-zA-z0-9_\-./]
	Path *string `json:"path"`

	// raw
	// Required: true
	Raw *CredentialRaw `json:"raw"`

	// type
	// Required: true
	// Enum: [ssh aws custom azure azure_storage gcp basic_auth elasticsearch swift]
	Type *string `json:"type"`
}

// Validate validates this create credential
func (m *CreateCredential) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCanonical(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePath(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRaw(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateCredential) validateCanonical(formats strfmt.Registry) error {

	if swag.IsZero(m.Canonical) { // not required
		return nil
	}

	if err := validate.MinLength("canonical", "body", string(m.Canonical), 3); err != nil {
		return err
	}

	if err := validate.MaxLength("canonical", "body", string(m.Canonical), 30); err != nil {
		return err
	}

	if err := validate.Pattern("canonical", "body", string(m.Canonical), `^[a-z0-9]+[a-z0-9\-_]+[a-z0-9]+$`); err != nil {
		return err
	}

	return nil
}

func (m *CreateCredential) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *CreateCredential) validatePath(formats strfmt.Registry) error {

	if err := validate.Required("path", "body", m.Path); err != nil {
		return err
	}

	if err := validate.Pattern("path", "body", string(*m.Path), `[a-zA-z0-9_\-./]`); err != nil {
		return err
	}

	return nil
}

func (m *CreateCredential) validateRaw(formats strfmt.Registry) error {

	if err := validate.Required("raw", "body", m.Raw); err != nil {
		return err
	}

	if m.Raw != nil {
		if err := m.Raw.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("raw")
			}
			return err
		}
	}

	return nil
}

var createCredentialTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["ssh","aws","custom","azure","azure_storage","gcp","basic_auth","elasticsearch","swift"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		createCredentialTypeTypePropEnum = append(createCredentialTypeTypePropEnum, v)
	}
}

const (

	// CreateCredentialTypeSSH captures enum value "ssh"
	CreateCredentialTypeSSH string = "ssh"

	// CreateCredentialTypeAws captures enum value "aws"
	CreateCredentialTypeAws string = "aws"

	// CreateCredentialTypeCustom captures enum value "custom"
	CreateCredentialTypeCustom string = "custom"

	// CreateCredentialTypeAzure captures enum value "azure"
	CreateCredentialTypeAzure string = "azure"

	// CreateCredentialTypeAzureStorage captures enum value "azure_storage"
	CreateCredentialTypeAzureStorage string = "azure_storage"

	// CreateCredentialTypeGcp captures enum value "gcp"
	CreateCredentialTypeGcp string = "gcp"

	// CreateCredentialTypeBasicAuth captures enum value "basic_auth"
	CreateCredentialTypeBasicAuth string = "basic_auth"

	// CreateCredentialTypeElasticsearch captures enum value "elasticsearch"
	CreateCredentialTypeElasticsearch string = "elasticsearch"

	// CreateCredentialTypeSwift captures enum value "swift"
	CreateCredentialTypeSwift string = "swift"
)

// prop value enum
func (m *CreateCredential) validateTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, createCredentialTypeTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *CreateCredential) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", *m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CreateCredential) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateCredential) UnmarshalBinary(b []byte) error {
	var res CreateCredential
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
