// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Plugin Plugin
//
// # The Plugin that holds all the Versions
//
// swagger:model Plugin
type Plugin struct {

	// id
	// Required: true
	// Minimum: 1
	ID *uint32 `json:"id"`

	// install
	Install *PluginInstall `json:"install,omitempty"`

	// latest
	Latest *PluginVersion `json:"latest,omitempty"`

	// Name assigned to the Plugin
	// Required: true
	Name *string `json:"name"`

	// If the plugin is owned
	// Required: true
	Owned *bool `json:"owned"`

	// registry
	// Required: true
	Registry *PluginRegistry `json:"registry"`

	// The relation of the Plugin with the current component, if any
	Relation *PluginRelation `json:"relation,omitempty"`
}

// Validate validates this plugin
func (m *Plugin) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInstall(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLatest(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOwned(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRegistry(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRelation(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Plugin) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	if err := validate.MinimumUint("id", "body", uint64(*m.ID), 1, false); err != nil {
		return err
	}

	return nil
}

func (m *Plugin) validateInstall(formats strfmt.Registry) error {
	if swag.IsZero(m.Install) { // not required
		return nil
	}

	if m.Install != nil {
		if err := m.Install.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("install")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("install")
			}

			return err
		}
	}

	return nil
}

func (m *Plugin) validateLatest(formats strfmt.Registry) error {
	if swag.IsZero(m.Latest) { // not required
		return nil
	}

	if m.Latest != nil {
		if err := m.Latest.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("latest")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("latest")
			}

			return err
		}
	}

	return nil
}

func (m *Plugin) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *Plugin) validateOwned(formats strfmt.Registry) error {

	if err := validate.Required("owned", "body", m.Owned); err != nil {
		return err
	}

	return nil
}

func (m *Plugin) validateRegistry(formats strfmt.Registry) error {

	if err := validate.Required("registry", "body", m.Registry); err != nil {
		return err
	}

	if m.Registry != nil {
		if err := m.Registry.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("registry")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("registry")
			}

			return err
		}
	}

	return nil
}

func (m *Plugin) validateRelation(formats strfmt.Registry) error {
	if swag.IsZero(m.Relation) { // not required
		return nil
	}

	if m.Relation != nil {
		if err := m.Relation.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("relation")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("relation")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this plugin based on the context it is used
func (m *Plugin) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateInstall(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateLatest(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRegistry(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRelation(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Plugin) contextValidateInstall(ctx context.Context, formats strfmt.Registry) error {

	if m.Install != nil {

		if swag.IsZero(m.Install) { // not required
			return nil
		}

		if err := m.Install.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("install")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("install")
			}

			return err
		}
	}

	return nil
}

func (m *Plugin) contextValidateLatest(ctx context.Context, formats strfmt.Registry) error {

	if m.Latest != nil {

		if swag.IsZero(m.Latest) { // not required
			return nil
		}

		if err := m.Latest.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("latest")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("latest")
			}

			return err
		}
	}

	return nil
}

func (m *Plugin) contextValidateRegistry(ctx context.Context, formats strfmt.Registry) error {

	if m.Registry != nil {

		if err := m.Registry.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("registry")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("registry")
			}

			return err
		}
	}

	return nil
}

func (m *Plugin) contextValidateRelation(ctx context.Context, formats strfmt.Registry) error {

	if m.Relation != nil {

		if swag.IsZero(m.Relation) { // not required
			return nil
		}

		if err := m.Relation.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("relation")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("relation")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Plugin) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Plugin) UnmarshalBinary(b []byte) error {
	var res Plugin
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
