// Code generated by go-swagger; DO NOT EDIT.

package organization_cloud_cost_management_accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/cycloidio/cycloid-cli/client/models"
)

// GetCloudCostManagementAccountsReader is a Reader for the GetCloudCostManagementAccounts structure.
type GetCloudCostManagementAccountsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCloudCostManagementAccountsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetCloudCostManagementAccountsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetCloudCostManagementAccountsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetCloudCostManagementAccountsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewGetCloudCostManagementAccountsUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewGetCloudCostManagementAccountsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetCloudCostManagementAccountsOK creates a GetCloudCostManagementAccountsOK with default headers values
func NewGetCloudCostManagementAccountsOK() *GetCloudCostManagementAccountsOK {
	return &GetCloudCostManagementAccountsOK{}
}

/*
GetCloudCostManagementAccountsOK describes a response with status code 200, with default header values.

List of Cloud Cost Management accounts.
*/
type GetCloudCostManagementAccountsOK struct {
	Payload *GetCloudCostManagementAccountsOKBody
}

// IsSuccess returns true when this get cloud cost management accounts o k response has a 2xx status code
func (o *GetCloudCostManagementAccountsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get cloud cost management accounts o k response has a 3xx status code
func (o *GetCloudCostManagementAccountsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get cloud cost management accounts o k response has a 4xx status code
func (o *GetCloudCostManagementAccountsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get cloud cost management accounts o k response has a 5xx status code
func (o *GetCloudCostManagementAccountsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get cloud cost management accounts o k response a status code equal to that given
func (o *GetCloudCostManagementAccountsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get cloud cost management accounts o k response
func (o *GetCloudCostManagementAccountsOK) Code() int {
	return 200
}

func (o *GetCloudCostManagementAccountsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/cloud_cost_management/accounts][%d] getCloudCostManagementAccountsOK %s", 200, payload)
}

func (o *GetCloudCostManagementAccountsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/cloud_cost_management/accounts][%d] getCloudCostManagementAccountsOK %s", 200, payload)
}

func (o *GetCloudCostManagementAccountsOK) GetPayload() *GetCloudCostManagementAccountsOKBody {
	return o.Payload
}

func (o *GetCloudCostManagementAccountsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetCloudCostManagementAccountsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCloudCostManagementAccountsForbidden creates a GetCloudCostManagementAccountsForbidden with default headers values
func NewGetCloudCostManagementAccountsForbidden() *GetCloudCostManagementAccountsForbidden {
	return &GetCloudCostManagementAccountsForbidden{}
}

/*
GetCloudCostManagementAccountsForbidden describes a response with status code 403, with default header values.

The authenticated user cannot perform the operation because, it doesn't have permissions for such operation.
*/
type GetCloudCostManagementAccountsForbidden struct {

	/* The length of the response body in octets (8-bit bytes).

	   Format: uint64
	*/
	ContentLength uint64

	Payload *models.ErrorPayload
}

// IsSuccess returns true when this get cloud cost management accounts forbidden response has a 2xx status code
func (o *GetCloudCostManagementAccountsForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get cloud cost management accounts forbidden response has a 3xx status code
func (o *GetCloudCostManagementAccountsForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get cloud cost management accounts forbidden response has a 4xx status code
func (o *GetCloudCostManagementAccountsForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get cloud cost management accounts forbidden response has a 5xx status code
func (o *GetCloudCostManagementAccountsForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get cloud cost management accounts forbidden response a status code equal to that given
func (o *GetCloudCostManagementAccountsForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get cloud cost management accounts forbidden response
func (o *GetCloudCostManagementAccountsForbidden) Code() int {
	return 403
}

func (o *GetCloudCostManagementAccountsForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/cloud_cost_management/accounts][%d] getCloudCostManagementAccountsForbidden %s", 403, payload)
}

func (o *GetCloudCostManagementAccountsForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/cloud_cost_management/accounts][%d] getCloudCostManagementAccountsForbidden %s", 403, payload)
}

func (o *GetCloudCostManagementAccountsForbidden) GetPayload() *models.ErrorPayload {
	return o.Payload
}

func (o *GetCloudCostManagementAccountsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Content-Length
	hdrContentLength := response.GetHeader("Content-Length")

	if hdrContentLength != "" {
		valcontentLength, err := swag.ConvertUint64(hdrContentLength)
		if err != nil {
			return errors.InvalidType("Content-Length", "header", "uint64", hdrContentLength)
		}
		o.ContentLength = valcontentLength
	}

	o.Payload = new(models.ErrorPayload)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCloudCostManagementAccountsNotFound creates a GetCloudCostManagementAccountsNotFound with default headers values
func NewGetCloudCostManagementAccountsNotFound() *GetCloudCostManagementAccountsNotFound {
	return &GetCloudCostManagementAccountsNotFound{}
}

/*
GetCloudCostManagementAccountsNotFound describes a response with status code 404, with default header values.

The response sent when any of the entities present in the path is not found.
*/
type GetCloudCostManagementAccountsNotFound struct {

	/* The length of the response body in octets (8-bit bytes).

	   Format: uint64
	*/
	ContentLength uint64

	Payload *models.ErrorPayload
}

// IsSuccess returns true when this get cloud cost management accounts not found response has a 2xx status code
func (o *GetCloudCostManagementAccountsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get cloud cost management accounts not found response has a 3xx status code
func (o *GetCloudCostManagementAccountsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get cloud cost management accounts not found response has a 4xx status code
func (o *GetCloudCostManagementAccountsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get cloud cost management accounts not found response has a 5xx status code
func (o *GetCloudCostManagementAccountsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get cloud cost management accounts not found response a status code equal to that given
func (o *GetCloudCostManagementAccountsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get cloud cost management accounts not found response
func (o *GetCloudCostManagementAccountsNotFound) Code() int {
	return 404
}

func (o *GetCloudCostManagementAccountsNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/cloud_cost_management/accounts][%d] getCloudCostManagementAccountsNotFound %s", 404, payload)
}

func (o *GetCloudCostManagementAccountsNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/cloud_cost_management/accounts][%d] getCloudCostManagementAccountsNotFound %s", 404, payload)
}

func (o *GetCloudCostManagementAccountsNotFound) GetPayload() *models.ErrorPayload {
	return o.Payload
}

func (o *GetCloudCostManagementAccountsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Content-Length
	hdrContentLength := response.GetHeader("Content-Length")

	if hdrContentLength != "" {
		valcontentLength, err := swag.ConvertUint64(hdrContentLength)
		if err != nil {
			return errors.InvalidType("Content-Length", "header", "uint64", hdrContentLength)
		}
		o.ContentLength = valcontentLength
	}

	o.Payload = new(models.ErrorPayload)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCloudCostManagementAccountsUnprocessableEntity creates a GetCloudCostManagementAccountsUnprocessableEntity with default headers values
func NewGetCloudCostManagementAccountsUnprocessableEntity() *GetCloudCostManagementAccountsUnprocessableEntity {
	return &GetCloudCostManagementAccountsUnprocessableEntity{}
}

/*
GetCloudCostManagementAccountsUnprocessableEntity describes a response with status code 422, with default header values.

All the custom errors that are generated from the Cycloid API
*/
type GetCloudCostManagementAccountsUnprocessableEntity struct {

	/* The length of the response body in octets (8-bit bytes).

	   Format: uint64
	*/
	ContentLength uint64

	Payload *models.ErrorPayload
}

// IsSuccess returns true when this get cloud cost management accounts unprocessable entity response has a 2xx status code
func (o *GetCloudCostManagementAccountsUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get cloud cost management accounts unprocessable entity response has a 3xx status code
func (o *GetCloudCostManagementAccountsUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get cloud cost management accounts unprocessable entity response has a 4xx status code
func (o *GetCloudCostManagementAccountsUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this get cloud cost management accounts unprocessable entity response has a 5xx status code
func (o *GetCloudCostManagementAccountsUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this get cloud cost management accounts unprocessable entity response a status code equal to that given
func (o *GetCloudCostManagementAccountsUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the get cloud cost management accounts unprocessable entity response
func (o *GetCloudCostManagementAccountsUnprocessableEntity) Code() int {
	return 422
}

func (o *GetCloudCostManagementAccountsUnprocessableEntity) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/cloud_cost_management/accounts][%d] getCloudCostManagementAccountsUnprocessableEntity %s", 422, payload)
}

func (o *GetCloudCostManagementAccountsUnprocessableEntity) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/cloud_cost_management/accounts][%d] getCloudCostManagementAccountsUnprocessableEntity %s", 422, payload)
}

func (o *GetCloudCostManagementAccountsUnprocessableEntity) GetPayload() *models.ErrorPayload {
	return o.Payload
}

func (o *GetCloudCostManagementAccountsUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Content-Length
	hdrContentLength := response.GetHeader("Content-Length")

	if hdrContentLength != "" {
		valcontentLength, err := swag.ConvertUint64(hdrContentLength)
		if err != nil {
			return errors.InvalidType("Content-Length", "header", "uint64", hdrContentLength)
		}
		o.ContentLength = valcontentLength
	}

	o.Payload = new(models.ErrorPayload)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCloudCostManagementAccountsDefault creates a GetCloudCostManagementAccountsDefault with default headers values
func NewGetCloudCostManagementAccountsDefault(code int) *GetCloudCostManagementAccountsDefault {
	return &GetCloudCostManagementAccountsDefault{
		_statusCode: code,
	}
}

/*
GetCloudCostManagementAccountsDefault describes a response with status code -1, with default header values.

The response sent when an unexpected error happened, as known as an internal server error.
*/
type GetCloudCostManagementAccountsDefault struct {
	_statusCode int

	/* The length of the response body in octets (8-bit bytes).

	   Format: uint64
	*/
	ContentLength uint64

	Payload *models.ErrorPayload
}

// IsSuccess returns true when this get cloud cost management accounts default response has a 2xx status code
func (o *GetCloudCostManagementAccountsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get cloud cost management accounts default response has a 3xx status code
func (o *GetCloudCostManagementAccountsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get cloud cost management accounts default response has a 4xx status code
func (o *GetCloudCostManagementAccountsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get cloud cost management accounts default response has a 5xx status code
func (o *GetCloudCostManagementAccountsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get cloud cost management accounts default response a status code equal to that given
func (o *GetCloudCostManagementAccountsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get cloud cost management accounts default response
func (o *GetCloudCostManagementAccountsDefault) Code() int {
	return o._statusCode
}

func (o *GetCloudCostManagementAccountsDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/cloud_cost_management/accounts][%d] getCloudCostManagementAccounts default %s", o._statusCode, payload)
}

func (o *GetCloudCostManagementAccountsDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/cloud_cost_management/accounts][%d] getCloudCostManagementAccounts default %s", o._statusCode, payload)
}

func (o *GetCloudCostManagementAccountsDefault) GetPayload() *models.ErrorPayload {
	return o.Payload
}

func (o *GetCloudCostManagementAccountsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Content-Length
	hdrContentLength := response.GetHeader("Content-Length")

	if hdrContentLength != "" {
		valcontentLength, err := swag.ConvertUint64(hdrContentLength)
		if err != nil {
			return errors.InvalidType("Content-Length", "header", "uint64", hdrContentLength)
		}
		o.ContentLength = valcontentLength
	}

	o.Payload = new(models.ErrorPayload)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
GetCloudCostManagementAccountsOKBody get cloud cost management accounts o k body
swagger:model GetCloudCostManagementAccountsOKBody
*/
type GetCloudCostManagementAccountsOKBody struct {

	// data
	// Required: true
	Data []*models.CloudCostManagementAccount `json:"data"`

	// pagination
	Pagination *models.Pagination `json:"pagination,omitempty"`
}

// Validate validates this get cloud cost management accounts o k body
func (o *GetCloudCostManagementAccountsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validatePagination(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCloudCostManagementAccountsOKBody) validateData(formats strfmt.Registry) error {

	if err := validate.Required("getCloudCostManagementAccountsOK"+"."+"data", "body", o.Data); err != nil {
		return err
	}

	for i := 0; i < len(o.Data); i++ {
		if swag.IsZero(o.Data[i]) { // not required
			continue
		}

		if o.Data[i] != nil {
			if err := o.Data[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("getCloudCostManagementAccountsOK" + "." + "data" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("getCloudCostManagementAccountsOK" + "." + "data" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (o *GetCloudCostManagementAccountsOKBody) validatePagination(formats strfmt.Registry) error {
	if swag.IsZero(o.Pagination) { // not required
		return nil
	}

	if o.Pagination != nil {
		if err := o.Pagination.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("getCloudCostManagementAccountsOK" + "." + "pagination")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("getCloudCostManagementAccountsOK" + "." + "pagination")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this get cloud cost management accounts o k body based on the context it is used
func (o *GetCloudCostManagementAccountsOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidatePagination(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCloudCostManagementAccountsOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Data); i++ {

		if o.Data[i] != nil {

			if swag.IsZero(o.Data[i]) { // not required
				return nil
			}

			if err := o.Data[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("getCloudCostManagementAccountsOK" + "." + "data" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("getCloudCostManagementAccountsOK" + "." + "data" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (o *GetCloudCostManagementAccountsOKBody) contextValidatePagination(ctx context.Context, formats strfmt.Registry) error {

	if o.Pagination != nil {

		if swag.IsZero(o.Pagination) { // not required
			return nil
		}

		if err := o.Pagination.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("getCloudCostManagementAccountsOK" + "." + "pagination")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("getCloudCostManagementAccountsOK" + "." + "pagination")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetCloudCostManagementAccountsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCloudCostManagementAccountsOKBody) UnmarshalBinary(b []byte) error {
	var res GetCloudCostManagementAccountsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
