// Code generated by go-swagger; DO NOT EDIT.

package organization_kpis

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cycloidio/cycloid-cli/client/models"
)

// CreateKpiReader is a Reader for the CreateKpi structure.
type CreateKpiReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateKpiReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateKpiOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewCreateKpiForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewCreateKpiUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewCreateKpiDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateKpiOK creates a CreateKpiOK with default headers values
func NewCreateKpiOK() *CreateKpiOK {
	return &CreateKpiOK{}
}

/*CreateKpiOK handles this case with default header values.

KPI has been configured
*/
type CreateKpiOK struct {
	Payload *CreateKpiOKBody
}

func (o *CreateKpiOK) Error() string {
	return fmt.Sprintf("[POST /organizations/{organization_canonical}/kpis][%d] createKpiOK  %+v", 200, o.Payload)
}

func (o *CreateKpiOK) GetPayload() *CreateKpiOKBody {
	return o.Payload
}

func (o *CreateKpiOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(CreateKpiOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateKpiForbidden creates a CreateKpiForbidden with default headers values
func NewCreateKpiForbidden() *CreateKpiForbidden {
	return &CreateKpiForbidden{}
}

/*CreateKpiForbidden handles this case with default header values.

The authenticated user cannot perform the operation because, it doesn't have permissions for such operation.
*/
type CreateKpiForbidden struct {
	Payload *models.ErrorPayload
}

func (o *CreateKpiForbidden) Error() string {
	return fmt.Sprintf("[POST /organizations/{organization_canonical}/kpis][%d] createKpiForbidden  %+v", 403, o.Payload)
}

func (o *CreateKpiForbidden) GetPayload() *models.ErrorPayload {
	return o.Payload
}

func (o *CreateKpiForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorPayload)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateKpiUnprocessableEntity creates a CreateKpiUnprocessableEntity with default headers values
func NewCreateKpiUnprocessableEntity() *CreateKpiUnprocessableEntity {
	return &CreateKpiUnprocessableEntity{}
}

/*CreateKpiUnprocessableEntity handles this case with default header values.

All the custom errors that are generated from the Cycloid API
*/
type CreateKpiUnprocessableEntity struct {
	Payload *models.ErrorPayload
}

func (o *CreateKpiUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /organizations/{organization_canonical}/kpis][%d] createKpiUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *CreateKpiUnprocessableEntity) GetPayload() *models.ErrorPayload {
	return o.Payload
}

func (o *CreateKpiUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorPayload)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateKpiDefault creates a CreateKpiDefault with default headers values
func NewCreateKpiDefault(code int) *CreateKpiDefault {
	return &CreateKpiDefault{
		_statusCode: code,
	}
}

/*CreateKpiDefault handles this case with default header values.

The response sent when an unexpected error happened, as known as an internal server error.
*/
type CreateKpiDefault struct {
	_statusCode int

	Payload *models.ErrorPayload
}

// Code gets the status code for the create kpi default response
func (o *CreateKpiDefault) Code() int {
	return o._statusCode
}

func (o *CreateKpiDefault) Error() string {
	return fmt.Sprintf("[POST /organizations/{organization_canonical}/kpis][%d] createKpi default  %+v", o._statusCode, o.Payload)
}

func (o *CreateKpiDefault) GetPayload() *models.ErrorPayload {
	return o.Payload
}

func (o *CreateKpiDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorPayload)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*CreateKpiOKBody create kpi o k body
swagger:model CreateKpiOKBody
*/
type CreateKpiOKBody struct {

	// data
	// Required: true
	Data *models.KPI `json:"data"`
}

// Validate validates this create kpi o k body
func (o *CreateKpiOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreateKpiOKBody) validateData(formats strfmt.Registry) error {

	if err := validate.Required("createKpiOK"+"."+"data", "body", o.Data); err != nil {
		return err
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("createKpiOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *CreateKpiOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateKpiOKBody) UnmarshalBinary(b []byte) error {
	var res CreateKpiOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
