// Code generated by go-swagger; DO NOT EDIT.

package cost_estimation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCostEstimateTfPlanParams creates a new CostEstimateTfPlanParams object
// with the default values initialized.
func NewCostEstimateTfPlanParams() *CostEstimateTfPlanParams {
	var ()
	return &CostEstimateTfPlanParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCostEstimateTfPlanParamsWithTimeout creates a new CostEstimateTfPlanParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCostEstimateTfPlanParamsWithTimeout(timeout time.Duration) *CostEstimateTfPlanParams {
	var ()
	return &CostEstimateTfPlanParams{

		timeout: timeout,
	}
}

// NewCostEstimateTfPlanParamsWithContext creates a new CostEstimateTfPlanParams object
// with the default values initialized, and the ability to set a context for a request
func NewCostEstimateTfPlanParamsWithContext(ctx context.Context) *CostEstimateTfPlanParams {
	var ()
	return &CostEstimateTfPlanParams{

		Context: ctx,
	}
}

// NewCostEstimateTfPlanParamsWithHTTPClient creates a new CostEstimateTfPlanParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCostEstimateTfPlanParamsWithHTTPClient(client *http.Client) *CostEstimateTfPlanParams {
	var ()
	return &CostEstimateTfPlanParams{
		HTTPClient: client,
	}
}

/*CostEstimateTfPlanParams contains all the parameters to send to the API endpoint
for the cost estimate tf plan operation typically these are written to a http.Request
*/
type CostEstimateTfPlanParams struct {

	/*Body
	  The project's attributes to check before to apply an infrastructure change.

	*/
	Body CostEstimateTfPlanBody
	/*OrganizationCanonical
	  A canonical of an organization.

	*/
	OrganizationCanonical string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the cost estimate tf plan params
func (o *CostEstimateTfPlanParams) WithTimeout(timeout time.Duration) *CostEstimateTfPlanParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the cost estimate tf plan params
func (o *CostEstimateTfPlanParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the cost estimate tf plan params
func (o *CostEstimateTfPlanParams) WithContext(ctx context.Context) *CostEstimateTfPlanParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the cost estimate tf plan params
func (o *CostEstimateTfPlanParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the cost estimate tf plan params
func (o *CostEstimateTfPlanParams) WithHTTPClient(client *http.Client) *CostEstimateTfPlanParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the cost estimate tf plan params
func (o *CostEstimateTfPlanParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the cost estimate tf plan params
func (o *CostEstimateTfPlanParams) WithBody(body CostEstimateTfPlanBody) *CostEstimateTfPlanParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the cost estimate tf plan params
func (o *CostEstimateTfPlanParams) SetBody(body CostEstimateTfPlanBody) {
	o.Body = body
}

// WithOrganizationCanonical adds the organizationCanonical to the cost estimate tf plan params
func (o *CostEstimateTfPlanParams) WithOrganizationCanonical(organizationCanonical string) *CostEstimateTfPlanParams {
	o.SetOrganizationCanonical(organizationCanonical)
	return o
}

// SetOrganizationCanonical adds the organizationCanonical to the cost estimate tf plan params
func (o *CostEstimateTfPlanParams) SetOrganizationCanonical(organizationCanonical string) {
	o.OrganizationCanonical = organizationCanonical
}

// WriteToRequest writes these params to a swagger request
func (o *CostEstimateTfPlanParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param organization_canonical
	if err := r.SetPathParam("organization_canonical", o.OrganizationCanonical); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
