// Code generated by go-swagger; DO NOT EDIT.

package organization_appearances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/cycloidio/cycloid-cli/client/models"
)

// DeleteAppearanceReader is a Reader for the DeleteAppearance structure.
type DeleteAppearanceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAppearanceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteAppearanceNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewDeleteAppearanceForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteAppearanceNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewDeleteAppearanceDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteAppearanceNoContent creates a DeleteAppearanceNoContent with default headers values
func NewDeleteAppearanceNoContent() *DeleteAppearanceNoContent {
	return &DeleteAppearanceNoContent{}
}

/*
DeleteAppearanceNoContent describes a response with status code 204, with default header values.

Organization appearance has been deleted.
*/
type DeleteAppearanceNoContent struct {
}

// IsSuccess returns true when this delete appearance no content response has a 2xx status code
func (o *DeleteAppearanceNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete appearance no content response has a 3xx status code
func (o *DeleteAppearanceNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete appearance no content response has a 4xx status code
func (o *DeleteAppearanceNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete appearance no content response has a 5xx status code
func (o *DeleteAppearanceNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete appearance no content response a status code equal to that given
func (o *DeleteAppearanceNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete appearance no content response
func (o *DeleteAppearanceNoContent) Code() int {
	return 204
}

func (o *DeleteAppearanceNoContent) Error() string {
	return fmt.Sprintf("[DELETE /organizations/{organization_canonical}/appearances/{appearance_canonical}][%d] deleteAppearanceNoContent", 204)
}

func (o *DeleteAppearanceNoContent) String() string {
	return fmt.Sprintf("[DELETE /organizations/{organization_canonical}/appearances/{appearance_canonical}][%d] deleteAppearanceNoContent", 204)
}

func (o *DeleteAppearanceNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAppearanceForbidden creates a DeleteAppearanceForbidden with default headers values
func NewDeleteAppearanceForbidden() *DeleteAppearanceForbidden {
	return &DeleteAppearanceForbidden{}
}

/*
DeleteAppearanceForbidden describes a response with status code 403, with default header values.

The authenticated user cannot perform the operation because, it doesn't have permissions for such operation.
*/
type DeleteAppearanceForbidden struct {

	/* The length of the response body in octets (8-bit bytes).

	   Format: uint64
	*/
	ContentLength uint64

	Payload *models.ErrorPayload
}

// IsSuccess returns true when this delete appearance forbidden response has a 2xx status code
func (o *DeleteAppearanceForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete appearance forbidden response has a 3xx status code
func (o *DeleteAppearanceForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete appearance forbidden response has a 4xx status code
func (o *DeleteAppearanceForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete appearance forbidden response has a 5xx status code
func (o *DeleteAppearanceForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this delete appearance forbidden response a status code equal to that given
func (o *DeleteAppearanceForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the delete appearance forbidden response
func (o *DeleteAppearanceForbidden) Code() int {
	return 403
}

func (o *DeleteAppearanceForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /organizations/{organization_canonical}/appearances/{appearance_canonical}][%d] deleteAppearanceForbidden %s", 403, payload)
}

func (o *DeleteAppearanceForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /organizations/{organization_canonical}/appearances/{appearance_canonical}][%d] deleteAppearanceForbidden %s", 403, payload)
}

func (o *DeleteAppearanceForbidden) GetPayload() *models.ErrorPayload {
	return o.Payload
}

func (o *DeleteAppearanceForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Content-Length
	hdrContentLength := response.GetHeader("Content-Length")

	if hdrContentLength != "" {
		valcontentLength, err := swag.ConvertUint64(hdrContentLength)
		if err != nil {
			return errors.InvalidType("Content-Length", "header", "uint64", hdrContentLength)
		}
		o.ContentLength = valcontentLength
	}

	o.Payload = new(models.ErrorPayload)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteAppearanceNotFound creates a DeleteAppearanceNotFound with default headers values
func NewDeleteAppearanceNotFound() *DeleteAppearanceNotFound {
	return &DeleteAppearanceNotFound{}
}

/*
DeleteAppearanceNotFound describes a response with status code 404, with default header values.

The response sent when any of the entities present in the path is not found.
*/
type DeleteAppearanceNotFound struct {

	/* The length of the response body in octets (8-bit bytes).

	   Format: uint64
	*/
	ContentLength uint64

	Payload *models.ErrorPayload
}

// IsSuccess returns true when this delete appearance not found response has a 2xx status code
func (o *DeleteAppearanceNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete appearance not found response has a 3xx status code
func (o *DeleteAppearanceNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete appearance not found response has a 4xx status code
func (o *DeleteAppearanceNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete appearance not found response has a 5xx status code
func (o *DeleteAppearanceNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete appearance not found response a status code equal to that given
func (o *DeleteAppearanceNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete appearance not found response
func (o *DeleteAppearanceNotFound) Code() int {
	return 404
}

func (o *DeleteAppearanceNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /organizations/{organization_canonical}/appearances/{appearance_canonical}][%d] deleteAppearanceNotFound %s", 404, payload)
}

func (o *DeleteAppearanceNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /organizations/{organization_canonical}/appearances/{appearance_canonical}][%d] deleteAppearanceNotFound %s", 404, payload)
}

func (o *DeleteAppearanceNotFound) GetPayload() *models.ErrorPayload {
	return o.Payload
}

func (o *DeleteAppearanceNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Content-Length
	hdrContentLength := response.GetHeader("Content-Length")

	if hdrContentLength != "" {
		valcontentLength, err := swag.ConvertUint64(hdrContentLength)
		if err != nil {
			return errors.InvalidType("Content-Length", "header", "uint64", hdrContentLength)
		}
		o.ContentLength = valcontentLength
	}

	o.Payload = new(models.ErrorPayload)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteAppearanceDefault creates a DeleteAppearanceDefault with default headers values
func NewDeleteAppearanceDefault(code int) *DeleteAppearanceDefault {
	return &DeleteAppearanceDefault{
		_statusCode: code,
	}
}

/*
DeleteAppearanceDefault describes a response with status code -1, with default header values.

The response sent when an unexpected error happened, as known as an internal server error.
*/
type DeleteAppearanceDefault struct {
	_statusCode int

	/* The length of the response body in octets (8-bit bytes).

	   Format: uint64
	*/
	ContentLength uint64

	Payload *models.ErrorPayload
}

// IsSuccess returns true when this delete appearance default response has a 2xx status code
func (o *DeleteAppearanceDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this delete appearance default response has a 3xx status code
func (o *DeleteAppearanceDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this delete appearance default response has a 4xx status code
func (o *DeleteAppearanceDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this delete appearance default response has a 5xx status code
func (o *DeleteAppearanceDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this delete appearance default response a status code equal to that given
func (o *DeleteAppearanceDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the delete appearance default response
func (o *DeleteAppearanceDefault) Code() int {
	return o._statusCode
}

func (o *DeleteAppearanceDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /organizations/{organization_canonical}/appearances/{appearance_canonical}][%d] deleteAppearance default %s", o._statusCode, payload)
}

func (o *DeleteAppearanceDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /organizations/{organization_canonical}/appearances/{appearance_canonical}][%d] deleteAppearance default %s", o._statusCode, payload)
}

func (o *DeleteAppearanceDefault) GetPayload() *models.ErrorPayload {
	return o.Payload
}

func (o *DeleteAppearanceDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Content-Length
	hdrContentLength := response.GetHeader("Content-Length")

	if hdrContentLength != "" {
		valcontentLength, err := swag.ConvertUint64(hdrContentLength)
		if err != nil {
			return errors.InvalidType("Content-Length", "header", "uint64", hdrContentLength)
		}
		o.ContentLength = valcontentLength
	}

	o.Payload = new(models.ErrorPayload)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
