// Code generated by go-swagger; DO NOT EDIT.

package organization_plugins

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/cycloidio/cycloid-cli/client/models"
)

// GetPluginReader is a Reader for the GetPlugin structure.
type GetPluginReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPluginReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetPluginOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetPluginForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetPluginNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewGetPluginDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetPluginOK creates a GetPluginOK with default headers values
func NewGetPluginOK() *GetPluginOK {
	return &GetPluginOK{}
}

/*
GetPluginOK describes a response with status code 200, with default header values.

The data of the Plugin
*/
type GetPluginOK struct {
	Payload *GetPluginOKBody
}

// IsSuccess returns true when this get plugin o k response has a 2xx status code
func (o *GetPluginOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get plugin o k response has a 3xx status code
func (o *GetPluginOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get plugin o k response has a 4xx status code
func (o *GetPluginOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get plugin o k response has a 5xx status code
func (o *GetPluginOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get plugin o k response a status code equal to that given
func (o *GetPluginOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get plugin o k response
func (o *GetPluginOK) Code() int {
	return 200
}

func (o *GetPluginOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/plugins/{plugin_install_id}][%d] getPluginOK %s", 200, payload)
}

func (o *GetPluginOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/plugins/{plugin_install_id}][%d] getPluginOK %s", 200, payload)
}

func (o *GetPluginOK) GetPayload() *GetPluginOKBody {
	return o.Payload
}

func (o *GetPluginOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetPluginOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetPluginForbidden creates a GetPluginForbidden with default headers values
func NewGetPluginForbidden() *GetPluginForbidden {
	return &GetPluginForbidden{}
}

/*
GetPluginForbidden describes a response with status code 403, with default header values.

The authenticated user cannot perform the operation because, it doesn't have permissions for such operation.
*/
type GetPluginForbidden struct {

	/* The length of the response body in octets (8-bit bytes).

	   Format: uint64
	*/
	ContentLength uint64

	Payload *models.ErrorPayload
}

// IsSuccess returns true when this get plugin forbidden response has a 2xx status code
func (o *GetPluginForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get plugin forbidden response has a 3xx status code
func (o *GetPluginForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get plugin forbidden response has a 4xx status code
func (o *GetPluginForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get plugin forbidden response has a 5xx status code
func (o *GetPluginForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get plugin forbidden response a status code equal to that given
func (o *GetPluginForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get plugin forbidden response
func (o *GetPluginForbidden) Code() int {
	return 403
}

func (o *GetPluginForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/plugins/{plugin_install_id}][%d] getPluginForbidden %s", 403, payload)
}

func (o *GetPluginForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/plugins/{plugin_install_id}][%d] getPluginForbidden %s", 403, payload)
}

func (o *GetPluginForbidden) GetPayload() *models.ErrorPayload {
	return o.Payload
}

func (o *GetPluginForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Content-Length
	hdrContentLength := response.GetHeader("Content-Length")

	if hdrContentLength != "" {
		valcontentLength, err := swag.ConvertUint64(hdrContentLength)
		if err != nil {
			return errors.InvalidType("Content-Length", "header", "uint64", hdrContentLength)
		}
		o.ContentLength = valcontentLength
	}

	o.Payload = new(models.ErrorPayload)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetPluginNotFound creates a GetPluginNotFound with default headers values
func NewGetPluginNotFound() *GetPluginNotFound {
	return &GetPluginNotFound{}
}

/*
GetPluginNotFound describes a response with status code 404, with default header values.

The response sent when any of the entities present in the path is not found.
*/
type GetPluginNotFound struct {

	/* The length of the response body in octets (8-bit bytes).

	   Format: uint64
	*/
	ContentLength uint64

	Payload *models.ErrorPayload
}

// IsSuccess returns true when this get plugin not found response has a 2xx status code
func (o *GetPluginNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get plugin not found response has a 3xx status code
func (o *GetPluginNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get plugin not found response has a 4xx status code
func (o *GetPluginNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get plugin not found response has a 5xx status code
func (o *GetPluginNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get plugin not found response a status code equal to that given
func (o *GetPluginNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get plugin not found response
func (o *GetPluginNotFound) Code() int {
	return 404
}

func (o *GetPluginNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/plugins/{plugin_install_id}][%d] getPluginNotFound %s", 404, payload)
}

func (o *GetPluginNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/plugins/{plugin_install_id}][%d] getPluginNotFound %s", 404, payload)
}

func (o *GetPluginNotFound) GetPayload() *models.ErrorPayload {
	return o.Payload
}

func (o *GetPluginNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Content-Length
	hdrContentLength := response.GetHeader("Content-Length")

	if hdrContentLength != "" {
		valcontentLength, err := swag.ConvertUint64(hdrContentLength)
		if err != nil {
			return errors.InvalidType("Content-Length", "header", "uint64", hdrContentLength)
		}
		o.ContentLength = valcontentLength
	}

	o.Payload = new(models.ErrorPayload)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetPluginDefault creates a GetPluginDefault with default headers values
func NewGetPluginDefault(code int) *GetPluginDefault {
	return &GetPluginDefault{
		_statusCode: code,
	}
}

/*
GetPluginDefault describes a response with status code -1, with default header values.

The response sent when an unexpected error happened, as known as an internal server error.
*/
type GetPluginDefault struct {
	_statusCode int

	/* The length of the response body in octets (8-bit bytes).

	   Format: uint64
	*/
	ContentLength uint64

	Payload *models.ErrorPayload
}

// IsSuccess returns true when this get plugin default response has a 2xx status code
func (o *GetPluginDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get plugin default response has a 3xx status code
func (o *GetPluginDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get plugin default response has a 4xx status code
func (o *GetPluginDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get plugin default response has a 5xx status code
func (o *GetPluginDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get plugin default response a status code equal to that given
func (o *GetPluginDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get plugin default response
func (o *GetPluginDefault) Code() int {
	return o._statusCode
}

func (o *GetPluginDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/plugins/{plugin_install_id}][%d] getPlugin default %s", o._statusCode, payload)
}

func (o *GetPluginDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/plugins/{plugin_install_id}][%d] getPlugin default %s", o._statusCode, payload)
}

func (o *GetPluginDefault) GetPayload() *models.ErrorPayload {
	return o.Payload
}

func (o *GetPluginDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Content-Length
	hdrContentLength := response.GetHeader("Content-Length")

	if hdrContentLength != "" {
		valcontentLength, err := swag.ConvertUint64(hdrContentLength)
		if err != nil {
			return errors.InvalidType("Content-Length", "header", "uint64", hdrContentLength)
		}
		o.ContentLength = valcontentLength
	}

	o.Payload = new(models.ErrorPayload)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

/*
GetPluginOKBody get plugin o k body
swagger:model GetPluginOKBody
*/
type GetPluginOKBody struct {

	// data
	// Required: true
	Data *models.Plugin `json:"data"`
}

// Validate validates this get plugin o k body
func (o *GetPluginOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetPluginOKBody) validateData(formats strfmt.Registry) error {

	if err := validate.Required("getPluginOK"+"."+"data", "body", o.Data); err != nil {
		return err
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("getPluginOK" + "." + "data")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("getPluginOK" + "." + "data")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this get plugin o k body based on the context it is used
func (o *GetPluginOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetPluginOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if o.Data != nil {

		if err := o.Data.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("getPluginOK" + "." + "data")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("getPluginOK" + "." + "data")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetPluginOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetPluginOKBody) UnmarshalBinary(b []byte) error {
	var res GetPluginOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
