// Code generated by go-swagger; DO NOT EDIT.

package organization_plugins

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/cycloidio/cycloid-cli/client/models"
)

// NewUpdatePluginParams creates a new UpdatePluginParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdatePluginParams() *UpdatePluginParams {
	return &UpdatePluginParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdatePluginParamsWithTimeout creates a new UpdatePluginParams object
// with the ability to set a timeout on a request.
func NewUpdatePluginParamsWithTimeout(timeout time.Duration) *UpdatePluginParams {
	return &UpdatePluginParams{
		timeout: timeout,
	}
}

// NewUpdatePluginParamsWithContext creates a new UpdatePluginParams object
// with the ability to set a context for a request.
func NewUpdatePluginParamsWithContext(ctx context.Context) *UpdatePluginParams {
	return &UpdatePluginParams{
		Context: ctx,
	}
}

// NewUpdatePluginParamsWithHTTPClient creates a new UpdatePluginParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdatePluginParamsWithHTTPClient(client *http.Client) *UpdatePluginParams {
	return &UpdatePluginParams{
		HTTPClient: client,
	}
}

/*
UpdatePluginParams contains all the parameters to send to the API endpoint

	for the update plugin operation.

	Typically these are written to a http.Request.
*/
type UpdatePluginParams struct {

	/* Body.

	   Data for the Plugin Install update
	*/
	Body *models.UpdatePluginInstall

	/* OrganizationCanonical.

	   A canonical of an organization.
	*/
	OrganizationCanonical string

	/* PluginInstallID.

	   A plugin install id

	   Format: uint32
	*/
	PluginInstallID uint32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update plugin params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdatePluginParams) WithDefaults() *UpdatePluginParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update plugin params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdatePluginParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update plugin params
func (o *UpdatePluginParams) WithTimeout(timeout time.Duration) *UpdatePluginParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update plugin params
func (o *UpdatePluginParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update plugin params
func (o *UpdatePluginParams) WithContext(ctx context.Context) *UpdatePluginParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update plugin params
func (o *UpdatePluginParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update plugin params
func (o *UpdatePluginParams) WithHTTPClient(client *http.Client) *UpdatePluginParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update plugin params
func (o *UpdatePluginParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update plugin params
func (o *UpdatePluginParams) WithBody(body *models.UpdatePluginInstall) *UpdatePluginParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update plugin params
func (o *UpdatePluginParams) SetBody(body *models.UpdatePluginInstall) {
	o.Body = body
}

// WithOrganizationCanonical adds the organizationCanonical to the update plugin params
func (o *UpdatePluginParams) WithOrganizationCanonical(organizationCanonical string) *UpdatePluginParams {
	o.SetOrganizationCanonical(organizationCanonical)
	return o
}

// SetOrganizationCanonical adds the organizationCanonical to the update plugin params
func (o *UpdatePluginParams) SetOrganizationCanonical(organizationCanonical string) {
	o.OrganizationCanonical = organizationCanonical
}

// WithPluginInstallID adds the pluginInstallID to the update plugin params
func (o *UpdatePluginParams) WithPluginInstallID(pluginInstallID uint32) *UpdatePluginParams {
	o.SetPluginInstallID(pluginInstallID)
	return o
}

// SetPluginInstallID adds the pluginInstallId to the update plugin params
func (o *UpdatePluginParams) SetPluginInstallID(pluginInstallID uint32) {
	o.PluginInstallID = pluginInstallID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdatePluginParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param organization_canonical
	if err := r.SetPathParam("organization_canonical", o.OrganizationCanonical); err != nil {
		return err
	}

	// path param plugin_install_id
	if err := r.SetPathParam("plugin_install_id", swag.FormatUint32(o.PluginInstallID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
