// Code generated by go-swagger; DO NOT EDIT.

package service_catalogs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cycloidio/cycloid-cli/client/models"
)

// CreateServiceCatalogFromTemplateReader is a Reader for the CreateServiceCatalogFromTemplate structure.
type CreateServiceCatalogFromTemplateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateServiceCatalogFromTemplateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateServiceCatalogFromTemplateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewCreateServiceCatalogFromTemplateForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateServiceCatalogFromTemplateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewCreateServiceCatalogFromTemplateUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewCreateServiceCatalogFromTemplateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateServiceCatalogFromTemplateOK creates a CreateServiceCatalogFromTemplateOK with default headers values
func NewCreateServiceCatalogFromTemplateOK() *CreateServiceCatalogFromTemplateOK {
	return &CreateServiceCatalogFromTemplateOK{}
}

/*CreateServiceCatalogFromTemplateOK handles this case with default header values.

The information of the service catalog.
*/
type CreateServiceCatalogFromTemplateOK struct {
	Payload *CreateServiceCatalogFromTemplateOKBody
}

func (o *CreateServiceCatalogFromTemplateOK) Error() string {
	return fmt.Sprintf("[POST /organizations/{organization_canonical}/service_catalogs/{service_catalog_ref}/template][%d] createServiceCatalogFromTemplateOK  %+v", 200, o.Payload)
}

func (o *CreateServiceCatalogFromTemplateOK) GetPayload() *CreateServiceCatalogFromTemplateOKBody {
	return o.Payload
}

func (o *CreateServiceCatalogFromTemplateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(CreateServiceCatalogFromTemplateOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateServiceCatalogFromTemplateForbidden creates a CreateServiceCatalogFromTemplateForbidden with default headers values
func NewCreateServiceCatalogFromTemplateForbidden() *CreateServiceCatalogFromTemplateForbidden {
	return &CreateServiceCatalogFromTemplateForbidden{}
}

/*CreateServiceCatalogFromTemplateForbidden handles this case with default header values.

The authenticated user cannot perform the operation because, it doesn't have permissions for such operation.
*/
type CreateServiceCatalogFromTemplateForbidden struct {
	/*The length of the response body in octets (8-bit bytes).
	 */
	ContentLength uint64

	Payload *models.ErrorPayload
}

func (o *CreateServiceCatalogFromTemplateForbidden) Error() string {
	return fmt.Sprintf("[POST /organizations/{organization_canonical}/service_catalogs/{service_catalog_ref}/template][%d] createServiceCatalogFromTemplateForbidden  %+v", 403, o.Payload)
}

func (o *CreateServiceCatalogFromTemplateForbidden) GetPayload() *models.ErrorPayload {
	return o.Payload
}

func (o *CreateServiceCatalogFromTemplateForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Content-Length
	contentLength, err := swag.ConvertUint64(response.GetHeader("Content-Length"))
	if err != nil {
		return errors.InvalidType("Content-Length", "header", "uint64", response.GetHeader("Content-Length"))
	}
	o.ContentLength = contentLength

	o.Payload = new(models.ErrorPayload)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateServiceCatalogFromTemplateNotFound creates a CreateServiceCatalogFromTemplateNotFound with default headers values
func NewCreateServiceCatalogFromTemplateNotFound() *CreateServiceCatalogFromTemplateNotFound {
	return &CreateServiceCatalogFromTemplateNotFound{}
}

/*CreateServiceCatalogFromTemplateNotFound handles this case with default header values.

The response sent when any of the entities present in the path is not found.
*/
type CreateServiceCatalogFromTemplateNotFound struct {
	/*The length of the response body in octets (8-bit bytes).
	 */
	ContentLength uint64

	Payload *models.ErrorPayload
}

func (o *CreateServiceCatalogFromTemplateNotFound) Error() string {
	return fmt.Sprintf("[POST /organizations/{organization_canonical}/service_catalogs/{service_catalog_ref}/template][%d] createServiceCatalogFromTemplateNotFound  %+v", 404, o.Payload)
}

func (o *CreateServiceCatalogFromTemplateNotFound) GetPayload() *models.ErrorPayload {
	return o.Payload
}

func (o *CreateServiceCatalogFromTemplateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Content-Length
	contentLength, err := swag.ConvertUint64(response.GetHeader("Content-Length"))
	if err != nil {
		return errors.InvalidType("Content-Length", "header", "uint64", response.GetHeader("Content-Length"))
	}
	o.ContentLength = contentLength

	o.Payload = new(models.ErrorPayload)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateServiceCatalogFromTemplateUnprocessableEntity creates a CreateServiceCatalogFromTemplateUnprocessableEntity with default headers values
func NewCreateServiceCatalogFromTemplateUnprocessableEntity() *CreateServiceCatalogFromTemplateUnprocessableEntity {
	return &CreateServiceCatalogFromTemplateUnprocessableEntity{}
}

/*CreateServiceCatalogFromTemplateUnprocessableEntity handles this case with default header values.

All the custom errors that are generated from the Cycloid API
*/
type CreateServiceCatalogFromTemplateUnprocessableEntity struct {
	/*The length of the response body in octets (8-bit bytes).
	 */
	ContentLength uint64

	Payload *models.ErrorPayload
}

func (o *CreateServiceCatalogFromTemplateUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /organizations/{organization_canonical}/service_catalogs/{service_catalog_ref}/template][%d] createServiceCatalogFromTemplateUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *CreateServiceCatalogFromTemplateUnprocessableEntity) GetPayload() *models.ErrorPayload {
	return o.Payload
}

func (o *CreateServiceCatalogFromTemplateUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Content-Length
	contentLength, err := swag.ConvertUint64(response.GetHeader("Content-Length"))
	if err != nil {
		return errors.InvalidType("Content-Length", "header", "uint64", response.GetHeader("Content-Length"))
	}
	o.ContentLength = contentLength

	o.Payload = new(models.ErrorPayload)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateServiceCatalogFromTemplateDefault creates a CreateServiceCatalogFromTemplateDefault with default headers values
func NewCreateServiceCatalogFromTemplateDefault(code int) *CreateServiceCatalogFromTemplateDefault {
	return &CreateServiceCatalogFromTemplateDefault{
		_statusCode: code,
	}
}

/*CreateServiceCatalogFromTemplateDefault handles this case with default header values.

The response sent when an unexpected error happened, as known as an internal server error.
*/
type CreateServiceCatalogFromTemplateDefault struct {
	_statusCode int

	/*The length of the response body in octets (8-bit bytes).
	 */
	ContentLength uint64

	Payload *models.ErrorPayload
}

// Code gets the status code for the create service catalog from template default response
func (o *CreateServiceCatalogFromTemplateDefault) Code() int {
	return o._statusCode
}

func (o *CreateServiceCatalogFromTemplateDefault) Error() string {
	return fmt.Sprintf("[POST /organizations/{organization_canonical}/service_catalogs/{service_catalog_ref}/template][%d] createServiceCatalogFromTemplate default  %+v", o._statusCode, o.Payload)
}

func (o *CreateServiceCatalogFromTemplateDefault) GetPayload() *models.ErrorPayload {
	return o.Payload
}

func (o *CreateServiceCatalogFromTemplateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Content-Length
	contentLength, err := swag.ConvertUint64(response.GetHeader("Content-Length"))
	if err != nil {
		return errors.InvalidType("Content-Length", "header", "uint64", response.GetHeader("Content-Length"))
	}
	o.ContentLength = contentLength

	o.Payload = new(models.ErrorPayload)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*CreateServiceCatalogFromTemplateOKBody create service catalog from template o k body
swagger:model CreateServiceCatalogFromTemplateOKBody
*/
type CreateServiceCatalogFromTemplateOKBody struct {

	// data
	// Required: true
	Data *models.ServiceCatalog `json:"data"`
}

// Validate validates this create service catalog from template o k body
func (o *CreateServiceCatalogFromTemplateOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreateServiceCatalogFromTemplateOKBody) validateData(formats strfmt.Registry) error {

	if err := validate.Required("createServiceCatalogFromTemplateOK"+"."+"data", "body", o.Data); err != nil {
		return err
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("createServiceCatalogFromTemplateOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *CreateServiceCatalogFromTemplateOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateServiceCatalogFromTemplateOKBody) UnmarshalBinary(b []byte) error {
	var res CreateServiceCatalogFromTemplateOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
