// Code generated by go-swagger; DO NOT EDIT.

package service_catalogs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/cycloidio/cycloid-cli/client/models"
)

// GetServiceCatalogTerraformImageReader is a Reader for the GetServiceCatalogTerraformImage structure.
type GetServiceCatalogTerraformImageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetServiceCatalogTerraformImageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetServiceCatalogTerraformImageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetServiceCatalogTerraformImageForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetServiceCatalogTerraformImageNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewGetServiceCatalogTerraformImageDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetServiceCatalogTerraformImageOK creates a GetServiceCatalogTerraformImageOK with default headers values
func NewGetServiceCatalogTerraformImageOK() *GetServiceCatalogTerraformImageOK {
	return &GetServiceCatalogTerraformImageOK{}
}

/*
GetServiceCatalogTerraformImageOK describes a response with status code 200, with default header values.

The SC TF Image
*/
type GetServiceCatalogTerraformImageOK struct {
	Payload *GetServiceCatalogTerraformImageOKBody
}

// IsSuccess returns true when this get service catalog terraform image o k response has a 2xx status code
func (o *GetServiceCatalogTerraformImageOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get service catalog terraform image o k response has a 3xx status code
func (o *GetServiceCatalogTerraformImageOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get service catalog terraform image o k response has a 4xx status code
func (o *GetServiceCatalogTerraformImageOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get service catalog terraform image o k response has a 5xx status code
func (o *GetServiceCatalogTerraformImageOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get service catalog terraform image o k response a status code equal to that given
func (o *GetServiceCatalogTerraformImageOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get service catalog terraform image o k response
func (o *GetServiceCatalogTerraformImageOK) Code() int {
	return 200
}

func (o *GetServiceCatalogTerraformImageOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/service_catalogs/{service_catalog_ref}/terraform/diagram/image][%d] getServiceCatalogTerraformImageOK %s", 200, payload)
}

func (o *GetServiceCatalogTerraformImageOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/service_catalogs/{service_catalog_ref}/terraform/diagram/image][%d] getServiceCatalogTerraformImageOK %s", 200, payload)
}

func (o *GetServiceCatalogTerraformImageOK) GetPayload() *GetServiceCatalogTerraformImageOKBody {
	return o.Payload
}

func (o *GetServiceCatalogTerraformImageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetServiceCatalogTerraformImageOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetServiceCatalogTerraformImageForbidden creates a GetServiceCatalogTerraformImageForbidden with default headers values
func NewGetServiceCatalogTerraformImageForbidden() *GetServiceCatalogTerraformImageForbidden {
	return &GetServiceCatalogTerraformImageForbidden{}
}

/*
GetServiceCatalogTerraformImageForbidden describes a response with status code 403, with default header values.

The authenticated user cannot perform the operation because, it doesn't have permissions for such operation.
*/
type GetServiceCatalogTerraformImageForbidden struct {

	/* The length of the response body in octets (8-bit bytes).

	   Format: uint64
	*/
	ContentLength uint64

	Payload *models.ErrorPayload
}

// IsSuccess returns true when this get service catalog terraform image forbidden response has a 2xx status code
func (o *GetServiceCatalogTerraformImageForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get service catalog terraform image forbidden response has a 3xx status code
func (o *GetServiceCatalogTerraformImageForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get service catalog terraform image forbidden response has a 4xx status code
func (o *GetServiceCatalogTerraformImageForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get service catalog terraform image forbidden response has a 5xx status code
func (o *GetServiceCatalogTerraformImageForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get service catalog terraform image forbidden response a status code equal to that given
func (o *GetServiceCatalogTerraformImageForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get service catalog terraform image forbidden response
func (o *GetServiceCatalogTerraformImageForbidden) Code() int {
	return 403
}

func (o *GetServiceCatalogTerraformImageForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/service_catalogs/{service_catalog_ref}/terraform/diagram/image][%d] getServiceCatalogTerraformImageForbidden %s", 403, payload)
}

func (o *GetServiceCatalogTerraformImageForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/service_catalogs/{service_catalog_ref}/terraform/diagram/image][%d] getServiceCatalogTerraformImageForbidden %s", 403, payload)
}

func (o *GetServiceCatalogTerraformImageForbidden) GetPayload() *models.ErrorPayload {
	return o.Payload
}

func (o *GetServiceCatalogTerraformImageForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Content-Length
	hdrContentLength := response.GetHeader("Content-Length")

	if hdrContentLength != "" {
		valcontentLength, err := swag.ConvertUint64(hdrContentLength)
		if err != nil {
			return errors.InvalidType("Content-Length", "header", "uint64", hdrContentLength)
		}
		o.ContentLength = valcontentLength
	}

	o.Payload = new(models.ErrorPayload)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetServiceCatalogTerraformImageNotFound creates a GetServiceCatalogTerraformImageNotFound with default headers values
func NewGetServiceCatalogTerraformImageNotFound() *GetServiceCatalogTerraformImageNotFound {
	return &GetServiceCatalogTerraformImageNotFound{}
}

/*
GetServiceCatalogTerraformImageNotFound describes a response with status code 404, with default header values.

The response sent when any of the entities present in the path is not found.
*/
type GetServiceCatalogTerraformImageNotFound struct {

	/* The length of the response body in octets (8-bit bytes).

	   Format: uint64
	*/
	ContentLength uint64

	Payload *models.ErrorPayload
}

// IsSuccess returns true when this get service catalog terraform image not found response has a 2xx status code
func (o *GetServiceCatalogTerraformImageNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get service catalog terraform image not found response has a 3xx status code
func (o *GetServiceCatalogTerraformImageNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get service catalog terraform image not found response has a 4xx status code
func (o *GetServiceCatalogTerraformImageNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get service catalog terraform image not found response has a 5xx status code
func (o *GetServiceCatalogTerraformImageNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get service catalog terraform image not found response a status code equal to that given
func (o *GetServiceCatalogTerraformImageNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get service catalog terraform image not found response
func (o *GetServiceCatalogTerraformImageNotFound) Code() int {
	return 404
}

func (o *GetServiceCatalogTerraformImageNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/service_catalogs/{service_catalog_ref}/terraform/diagram/image][%d] getServiceCatalogTerraformImageNotFound %s", 404, payload)
}

func (o *GetServiceCatalogTerraformImageNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/service_catalogs/{service_catalog_ref}/terraform/diagram/image][%d] getServiceCatalogTerraformImageNotFound %s", 404, payload)
}

func (o *GetServiceCatalogTerraformImageNotFound) GetPayload() *models.ErrorPayload {
	return o.Payload
}

func (o *GetServiceCatalogTerraformImageNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Content-Length
	hdrContentLength := response.GetHeader("Content-Length")

	if hdrContentLength != "" {
		valcontentLength, err := swag.ConvertUint64(hdrContentLength)
		if err != nil {
			return errors.InvalidType("Content-Length", "header", "uint64", hdrContentLength)
		}
		o.ContentLength = valcontentLength
	}

	o.Payload = new(models.ErrorPayload)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetServiceCatalogTerraformImageDefault creates a GetServiceCatalogTerraformImageDefault with default headers values
func NewGetServiceCatalogTerraformImageDefault(code int) *GetServiceCatalogTerraformImageDefault {
	return &GetServiceCatalogTerraformImageDefault{
		_statusCode: code,
	}
}

/*
GetServiceCatalogTerraformImageDefault describes a response with status code -1, with default header values.

The response sent when an unexpected error happened, as known as an internal server error.
*/
type GetServiceCatalogTerraformImageDefault struct {
	_statusCode int

	/* The length of the response body in octets (8-bit bytes).

	   Format: uint64
	*/
	ContentLength uint64

	Payload *models.ErrorPayload
}

// IsSuccess returns true when this get service catalog terraform image default response has a 2xx status code
func (o *GetServiceCatalogTerraformImageDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get service catalog terraform image default response has a 3xx status code
func (o *GetServiceCatalogTerraformImageDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get service catalog terraform image default response has a 4xx status code
func (o *GetServiceCatalogTerraformImageDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get service catalog terraform image default response has a 5xx status code
func (o *GetServiceCatalogTerraformImageDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get service catalog terraform image default response a status code equal to that given
func (o *GetServiceCatalogTerraformImageDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get service catalog terraform image default response
func (o *GetServiceCatalogTerraformImageDefault) Code() int {
	return o._statusCode
}

func (o *GetServiceCatalogTerraformImageDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/service_catalogs/{service_catalog_ref}/terraform/diagram/image][%d] getServiceCatalogTerraformImage default %s", o._statusCode, payload)
}

func (o *GetServiceCatalogTerraformImageDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/service_catalogs/{service_catalog_ref}/terraform/diagram/image][%d] getServiceCatalogTerraformImage default %s", o._statusCode, payload)
}

func (o *GetServiceCatalogTerraformImageDefault) GetPayload() *models.ErrorPayload {
	return o.Payload
}

func (o *GetServiceCatalogTerraformImageDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Content-Length
	hdrContentLength := response.GetHeader("Content-Length")

	if hdrContentLength != "" {
		valcontentLength, err := swag.ConvertUint64(hdrContentLength)
		if err != nil {
			return errors.InvalidType("Content-Length", "header", "uint64", hdrContentLength)
		}
		o.ContentLength = valcontentLength
	}

	o.Payload = new(models.ErrorPayload)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
GetServiceCatalogTerraformImageOKBody get service catalog terraform image o k body
swagger:model GetServiceCatalogTerraformImageOKBody
*/
type GetServiceCatalogTerraformImageOKBody struct {

	// data
	// Required: true
	Data *models.TerraformImage `json:"data"`
}

// Validate validates this get service catalog terraform image o k body
func (o *GetServiceCatalogTerraformImageOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetServiceCatalogTerraformImageOKBody) validateData(formats strfmt.Registry) error {

	if err := validate.Required("getServiceCatalogTerraformImageOK"+"."+"data", "body", o.Data); err != nil {
		return err
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getServiceCatalogTerraformImageOK" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getServiceCatalogTerraformImageOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this get service catalog terraform image o k body based on the context it is used
func (o *GetServiceCatalogTerraformImageOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetServiceCatalogTerraformImageOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if o.Data != nil {

		if err := o.Data.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getServiceCatalogTerraformImageOK" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getServiceCatalogTerraformImageOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetServiceCatalogTerraformImageOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetServiceCatalogTerraformImageOKBody) UnmarshalBinary(b []byte) error {
	var res GetServiceCatalogTerraformImageOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
