// Code generated by go-swagger; DO NOT EDIT.

package service_catalogs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetServiceCatalogParams creates a new GetServiceCatalogParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetServiceCatalogParams() *GetServiceCatalogParams {
	return &GetServiceCatalogParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetServiceCatalogParamsWithTimeout creates a new GetServiceCatalogParams object
// with the ability to set a timeout on a request.
func NewGetServiceCatalogParamsWithTimeout(timeout time.Duration) *GetServiceCatalogParams {
	return &GetServiceCatalogParams{
		timeout: timeout,
	}
}

// NewGetServiceCatalogParamsWithContext creates a new GetServiceCatalogParams object
// with the ability to set a context for a request.
func NewGetServiceCatalogParamsWithContext(ctx context.Context) *GetServiceCatalogParams {
	return &GetServiceCatalogParams{
		Context: ctx,
	}
}

// NewGetServiceCatalogParamsWithHTTPClient creates a new GetServiceCatalogParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetServiceCatalogParamsWithHTTPClient(client *http.Client) *GetServiceCatalogParams {
	return &GetServiceCatalogParams{
		HTTPClient: client,
	}
}

/*
GetServiceCatalogParams contains all the parameters to send to the API endpoint

	for the get service catalog operation.

	Typically these are written to a http.Request.
*/
type GetServiceCatalogParams struct {

	/* OrganizationCanonical.

	   A canonical of an organization.
	*/
	OrganizationCanonical string

	/* ServiceCatalogRef.

	   A Service Catalog name
	*/
	ServiceCatalogRef string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get service catalog params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetServiceCatalogParams) WithDefaults() *GetServiceCatalogParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get service catalog params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetServiceCatalogParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get service catalog params
func (o *GetServiceCatalogParams) WithTimeout(timeout time.Duration) *GetServiceCatalogParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get service catalog params
func (o *GetServiceCatalogParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get service catalog params
func (o *GetServiceCatalogParams) WithContext(ctx context.Context) *GetServiceCatalogParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get service catalog params
func (o *GetServiceCatalogParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get service catalog params
func (o *GetServiceCatalogParams) WithHTTPClient(client *http.Client) *GetServiceCatalogParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get service catalog params
func (o *GetServiceCatalogParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrganizationCanonical adds the organizationCanonical to the get service catalog params
func (o *GetServiceCatalogParams) WithOrganizationCanonical(organizationCanonical string) *GetServiceCatalogParams {
	o.SetOrganizationCanonical(organizationCanonical)
	return o
}

// SetOrganizationCanonical adds the organizationCanonical to the get service catalog params
func (o *GetServiceCatalogParams) SetOrganizationCanonical(organizationCanonical string) {
	o.OrganizationCanonical = organizationCanonical
}

// WithServiceCatalogRef adds the serviceCatalogRef to the get service catalog params
func (o *GetServiceCatalogParams) WithServiceCatalogRef(serviceCatalogRef string) *GetServiceCatalogParams {
	o.SetServiceCatalogRef(serviceCatalogRef)
	return o
}

// SetServiceCatalogRef adds the serviceCatalogRef to the get service catalog params
func (o *GetServiceCatalogParams) SetServiceCatalogRef(serviceCatalogRef string) {
	o.ServiceCatalogRef = serviceCatalogRef
}

// WriteToRequest writes these params to a swagger request
func (o *GetServiceCatalogParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param organization_canonical
	if err := r.SetPathParam("organization_canonical", o.OrganizationCanonical); err != nil {
		return err
	}

	// path param service_catalog_ref
	if err := r.SetPathParam("service_catalog_ref", o.ServiceCatalogRef); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
