// Code generated by go-swagger; DO NOT EDIT.

package service_catalogs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewValidateServiceCatalogDependenciesParams creates a new ValidateServiceCatalogDependenciesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewValidateServiceCatalogDependenciesParams() *ValidateServiceCatalogDependenciesParams {
	return &ValidateServiceCatalogDependenciesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewValidateServiceCatalogDependenciesParamsWithTimeout creates a new ValidateServiceCatalogDependenciesParams object
// with the ability to set a timeout on a request.
func NewValidateServiceCatalogDependenciesParamsWithTimeout(timeout time.Duration) *ValidateServiceCatalogDependenciesParams {
	return &ValidateServiceCatalogDependenciesParams{
		timeout: timeout,
	}
}

// NewValidateServiceCatalogDependenciesParamsWithContext creates a new ValidateServiceCatalogDependenciesParams object
// with the ability to set a context for a request.
func NewValidateServiceCatalogDependenciesParamsWithContext(ctx context.Context) *ValidateServiceCatalogDependenciesParams {
	return &ValidateServiceCatalogDependenciesParams{
		Context: ctx,
	}
}

// NewValidateServiceCatalogDependenciesParamsWithHTTPClient creates a new ValidateServiceCatalogDependenciesParams object
// with the ability to set a custom HTTPClient for a request.
func NewValidateServiceCatalogDependenciesParamsWithHTTPClient(client *http.Client) *ValidateServiceCatalogDependenciesParams {
	return &ValidateServiceCatalogDependenciesParams{
		HTTPClient: client,
	}
}

/*
ValidateServiceCatalogDependenciesParams contains all the parameters to send to the API endpoint

	for the validate service catalog dependencies operation.

	Typically these are written to a http.Request.
*/
type ValidateServiceCatalogDependenciesParams struct {

	/* OrganizationCanonical.

	   A canonical of an organization.
	*/
	OrganizationCanonical string

	/* ServiceCatalogRef.

	   A Service Catalog name
	*/
	ServiceCatalogRef string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the validate service catalog dependencies params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ValidateServiceCatalogDependenciesParams) WithDefaults() *ValidateServiceCatalogDependenciesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the validate service catalog dependencies params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ValidateServiceCatalogDependenciesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the validate service catalog dependencies params
func (o *ValidateServiceCatalogDependenciesParams) WithTimeout(timeout time.Duration) *ValidateServiceCatalogDependenciesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the validate service catalog dependencies params
func (o *ValidateServiceCatalogDependenciesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the validate service catalog dependencies params
func (o *ValidateServiceCatalogDependenciesParams) WithContext(ctx context.Context) *ValidateServiceCatalogDependenciesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the validate service catalog dependencies params
func (o *ValidateServiceCatalogDependenciesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the validate service catalog dependencies params
func (o *ValidateServiceCatalogDependenciesParams) WithHTTPClient(client *http.Client) *ValidateServiceCatalogDependenciesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the validate service catalog dependencies params
func (o *ValidateServiceCatalogDependenciesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrganizationCanonical adds the organizationCanonical to the validate service catalog dependencies params
func (o *ValidateServiceCatalogDependenciesParams) WithOrganizationCanonical(organizationCanonical string) *ValidateServiceCatalogDependenciesParams {
	o.SetOrganizationCanonical(organizationCanonical)
	return o
}

// SetOrganizationCanonical adds the organizationCanonical to the validate service catalog dependencies params
func (o *ValidateServiceCatalogDependenciesParams) SetOrganizationCanonical(organizationCanonical string) {
	o.OrganizationCanonical = organizationCanonical
}

// WithServiceCatalogRef adds the serviceCatalogRef to the validate service catalog dependencies params
func (o *ValidateServiceCatalogDependenciesParams) WithServiceCatalogRef(serviceCatalogRef string) *ValidateServiceCatalogDependenciesParams {
	o.SetServiceCatalogRef(serviceCatalogRef)
	return o
}

// SetServiceCatalogRef adds the serviceCatalogRef to the validate service catalog dependencies params
func (o *ValidateServiceCatalogDependenciesParams) SetServiceCatalogRef(serviceCatalogRef string) {
	o.ServiceCatalogRef = serviceCatalogRef
}

// WriteToRequest writes these params to a swagger request
func (o *ValidateServiceCatalogDependenciesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param organization_canonical
	if err := r.SetPathParam("organization_canonical", o.OrganizationCanonical); err != nil {
		return err
	}

	// path param service_catalog_ref
	if err := r.SetPathParam("service_catalog_ref", o.ServiceCatalogRef); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
