// Code generated by go-swagger; DO NOT EDIT.

package component_pipelines_jobs_builds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/cycloidio/cycloid-cli/client/models"
)

// GetBuildPreparationReader is a Reader for the GetBuildPreparation structure.
type GetBuildPreparationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBuildPreparationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetBuildPreparationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetBuildPreparationForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetBuildPreparationNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewGetBuildPreparationDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetBuildPreparationOK creates a GetBuildPreparationOK with default headers values
func NewGetBuildPreparationOK() *GetBuildPreparationOK {
	return &GetBuildPreparationOK{}
}

/*
GetBuildPreparationOK describes a response with status code 200, with default header values.

Return the Preparation
*/
type GetBuildPreparationOK struct {
	Payload *GetBuildPreparationOKBody
}

// IsSuccess returns true when this get build preparation o k response has a 2xx status code
func (o *GetBuildPreparationOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get build preparation o k response has a 3xx status code
func (o *GetBuildPreparationOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get build preparation o k response has a 4xx status code
func (o *GetBuildPreparationOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get build preparation o k response has a 5xx status code
func (o *GetBuildPreparationOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get build preparation o k response a status code equal to that given
func (o *GetBuildPreparationOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get build preparation o k response
func (o *GetBuildPreparationOK) Code() int {
	return 200
}

func (o *GetBuildPreparationOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/projects/{project_canonical}/environments/{environment_canonical}/components/{component_canonical}/pipelines/{inpath_pipeline_name}/jobs/{job_name}/builds/{build_id}/preparation][%d] getBuildPreparationOK %s", 200, payload)
}

func (o *GetBuildPreparationOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/projects/{project_canonical}/environments/{environment_canonical}/components/{component_canonical}/pipelines/{inpath_pipeline_name}/jobs/{job_name}/builds/{build_id}/preparation][%d] getBuildPreparationOK %s", 200, payload)
}

func (o *GetBuildPreparationOK) GetPayload() *GetBuildPreparationOKBody {
	return o.Payload
}

func (o *GetBuildPreparationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetBuildPreparationOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBuildPreparationForbidden creates a GetBuildPreparationForbidden with default headers values
func NewGetBuildPreparationForbidden() *GetBuildPreparationForbidden {
	return &GetBuildPreparationForbidden{}
}

/*
GetBuildPreparationForbidden describes a response with status code 403, with default header values.

The authenticated user cannot perform the operation because, it doesn't have permissions for such operation.
*/
type GetBuildPreparationForbidden struct {

	/* The length of the response body in octets (8-bit bytes).

	   Format: uint64
	*/
	ContentLength uint64

	Payload *models.ErrorPayload
}

// IsSuccess returns true when this get build preparation forbidden response has a 2xx status code
func (o *GetBuildPreparationForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get build preparation forbidden response has a 3xx status code
func (o *GetBuildPreparationForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get build preparation forbidden response has a 4xx status code
func (o *GetBuildPreparationForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get build preparation forbidden response has a 5xx status code
func (o *GetBuildPreparationForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get build preparation forbidden response a status code equal to that given
func (o *GetBuildPreparationForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get build preparation forbidden response
func (o *GetBuildPreparationForbidden) Code() int {
	return 403
}

func (o *GetBuildPreparationForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/projects/{project_canonical}/environments/{environment_canonical}/components/{component_canonical}/pipelines/{inpath_pipeline_name}/jobs/{job_name}/builds/{build_id}/preparation][%d] getBuildPreparationForbidden %s", 403, payload)
}

func (o *GetBuildPreparationForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/projects/{project_canonical}/environments/{environment_canonical}/components/{component_canonical}/pipelines/{inpath_pipeline_name}/jobs/{job_name}/builds/{build_id}/preparation][%d] getBuildPreparationForbidden %s", 403, payload)
}

func (o *GetBuildPreparationForbidden) GetPayload() *models.ErrorPayload {
	return o.Payload
}

func (o *GetBuildPreparationForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Content-Length
	hdrContentLength := response.GetHeader("Content-Length")

	if hdrContentLength != "" {
		valcontentLength, err := swag.ConvertUint64(hdrContentLength)
		if err != nil {
			return errors.InvalidType("Content-Length", "header", "uint64", hdrContentLength)
		}
		o.ContentLength = valcontentLength
	}

	o.Payload = new(models.ErrorPayload)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBuildPreparationNotFound creates a GetBuildPreparationNotFound with default headers values
func NewGetBuildPreparationNotFound() *GetBuildPreparationNotFound {
	return &GetBuildPreparationNotFound{}
}

/*
GetBuildPreparationNotFound describes a response with status code 404, with default header values.

The response sent when any of the entities present in the path is not found.
*/
type GetBuildPreparationNotFound struct {

	/* The length of the response body in octets (8-bit bytes).

	   Format: uint64
	*/
	ContentLength uint64

	Payload *models.ErrorPayload
}

// IsSuccess returns true when this get build preparation not found response has a 2xx status code
func (o *GetBuildPreparationNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get build preparation not found response has a 3xx status code
func (o *GetBuildPreparationNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get build preparation not found response has a 4xx status code
func (o *GetBuildPreparationNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get build preparation not found response has a 5xx status code
func (o *GetBuildPreparationNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get build preparation not found response a status code equal to that given
func (o *GetBuildPreparationNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get build preparation not found response
func (o *GetBuildPreparationNotFound) Code() int {
	return 404
}

func (o *GetBuildPreparationNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/projects/{project_canonical}/environments/{environment_canonical}/components/{component_canonical}/pipelines/{inpath_pipeline_name}/jobs/{job_name}/builds/{build_id}/preparation][%d] getBuildPreparationNotFound %s", 404, payload)
}

func (o *GetBuildPreparationNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/projects/{project_canonical}/environments/{environment_canonical}/components/{component_canonical}/pipelines/{inpath_pipeline_name}/jobs/{job_name}/builds/{build_id}/preparation][%d] getBuildPreparationNotFound %s", 404, payload)
}

func (o *GetBuildPreparationNotFound) GetPayload() *models.ErrorPayload {
	return o.Payload
}

func (o *GetBuildPreparationNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Content-Length
	hdrContentLength := response.GetHeader("Content-Length")

	if hdrContentLength != "" {
		valcontentLength, err := swag.ConvertUint64(hdrContentLength)
		if err != nil {
			return errors.InvalidType("Content-Length", "header", "uint64", hdrContentLength)
		}
		o.ContentLength = valcontentLength
	}

	o.Payload = new(models.ErrorPayload)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBuildPreparationDefault creates a GetBuildPreparationDefault with default headers values
func NewGetBuildPreparationDefault(code int) *GetBuildPreparationDefault {
	return &GetBuildPreparationDefault{
		_statusCode: code,
	}
}

/*
GetBuildPreparationDefault describes a response with status code -1, with default header values.

The response sent when an unexpected error happened, as known as an internal server error.
*/
type GetBuildPreparationDefault struct {
	_statusCode int

	/* The length of the response body in octets (8-bit bytes).

	   Format: uint64
	*/
	ContentLength uint64

	Payload *models.ErrorPayload
}

// IsSuccess returns true when this get build preparation default response has a 2xx status code
func (o *GetBuildPreparationDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get build preparation default response has a 3xx status code
func (o *GetBuildPreparationDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get build preparation default response has a 4xx status code
func (o *GetBuildPreparationDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get build preparation default response has a 5xx status code
func (o *GetBuildPreparationDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get build preparation default response a status code equal to that given
func (o *GetBuildPreparationDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get build preparation default response
func (o *GetBuildPreparationDefault) Code() int {
	return o._statusCode
}

func (o *GetBuildPreparationDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/projects/{project_canonical}/environments/{environment_canonical}/components/{component_canonical}/pipelines/{inpath_pipeline_name}/jobs/{job_name}/builds/{build_id}/preparation][%d] getBuildPreparation default %s", o._statusCode, payload)
}

func (o *GetBuildPreparationDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations/{organization_canonical}/projects/{project_canonical}/environments/{environment_canonical}/components/{component_canonical}/pipelines/{inpath_pipeline_name}/jobs/{job_name}/builds/{build_id}/preparation][%d] getBuildPreparation default %s", o._statusCode, payload)
}

func (o *GetBuildPreparationDefault) GetPayload() *models.ErrorPayload {
	return o.Payload
}

func (o *GetBuildPreparationDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Content-Length
	hdrContentLength := response.GetHeader("Content-Length")

	if hdrContentLength != "" {
		valcontentLength, err := swag.ConvertUint64(hdrContentLength)
		if err != nil {
			return errors.InvalidType("Content-Length", "header", "uint64", hdrContentLength)
		}
		o.ContentLength = valcontentLength
	}

	o.Payload = new(models.ErrorPayload)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
GetBuildPreparationOKBody get build preparation o k body
swagger:model GetBuildPreparationOKBody
*/
type GetBuildPreparationOKBody struct {

	// data
	// Required: true
	Data *models.Preparation `json:"data"`
}

// Validate validates this get build preparation o k body
func (o *GetBuildPreparationOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetBuildPreparationOKBody) validateData(formats strfmt.Registry) error {

	if err := validate.Required("getBuildPreparationOK"+"."+"data", "body", o.Data); err != nil {
		return err
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getBuildPreparationOK" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getBuildPreparationOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this get build preparation o k body based on the context it is used
func (o *GetBuildPreparationOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetBuildPreparationOKBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if o.Data != nil {

		if err := o.Data.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getBuildPreparationOK" + "." + "data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getBuildPreparationOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetBuildPreparationOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetBuildPreparationOKBody) UnmarshalBinary(b []byte) error {
	var res GetBuildPreparationOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
