// Code generated by go-swagger; DO NOT EDIT.

package component_pipelines_jobs_builds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetBuildPlanParams creates a new GetBuildPlanParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetBuildPlanParams() *GetBuildPlanParams {
	return &GetBuildPlanParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetBuildPlanParamsWithTimeout creates a new GetBuildPlanParams object
// with the ability to set a timeout on a request.
func NewGetBuildPlanParamsWithTimeout(timeout time.Duration) *GetBuildPlanParams {
	return &GetBuildPlanParams{
		timeout: timeout,
	}
}

// NewGetBuildPlanParamsWithContext creates a new GetBuildPlanParams object
// with the ability to set a context for a request.
func NewGetBuildPlanParamsWithContext(ctx context.Context) *GetBuildPlanParams {
	return &GetBuildPlanParams{
		Context: ctx,
	}
}

// NewGetBuildPlanParamsWithHTTPClient creates a new GetBuildPlanParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetBuildPlanParamsWithHTTPClient(client *http.Client) *GetBuildPlanParams {
	return &GetBuildPlanParams{
		HTTPClient: client,
	}
}

/*
GetBuildPlanParams contains all the parameters to send to the API endpoint

	for the get build plan operation.

	Typically these are written to a http.Request.
*/
type GetBuildPlanParams struct {

	/* BuildID.

	   A build id
	*/
	BuildID string

	/* ComponentCanonical.

	   A canonical of a component.
	*/
	ComponentCanonical string

	/* EnvironmentCanonical.

	   The environment canonical to use as part of a path
	*/
	EnvironmentCanonical string

	/* InpathPipelineName.

	   A pipeline name
	*/
	InpathPipelineName string

	/* JobName.

	   A job name
	*/
	JobName string

	/* OrganizationCanonical.

	   A canonical of an organization.
	*/
	OrganizationCanonical string

	/* ProjectCanonical.

	   A canonical of a project.
	*/
	ProjectCanonical string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get build plan params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBuildPlanParams) WithDefaults() *GetBuildPlanParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get build plan params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBuildPlanParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get build plan params
func (o *GetBuildPlanParams) WithTimeout(timeout time.Duration) *GetBuildPlanParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get build plan params
func (o *GetBuildPlanParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get build plan params
func (o *GetBuildPlanParams) WithContext(ctx context.Context) *GetBuildPlanParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get build plan params
func (o *GetBuildPlanParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get build plan params
func (o *GetBuildPlanParams) WithHTTPClient(client *http.Client) *GetBuildPlanParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get build plan params
func (o *GetBuildPlanParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBuildID adds the buildID to the get build plan params
func (o *GetBuildPlanParams) WithBuildID(buildID string) *GetBuildPlanParams {
	o.SetBuildID(buildID)
	return o
}

// SetBuildID adds the buildId to the get build plan params
func (o *GetBuildPlanParams) SetBuildID(buildID string) {
	o.BuildID = buildID
}

// WithComponentCanonical adds the componentCanonical to the get build plan params
func (o *GetBuildPlanParams) WithComponentCanonical(componentCanonical string) *GetBuildPlanParams {
	o.SetComponentCanonical(componentCanonical)
	return o
}

// SetComponentCanonical adds the componentCanonical to the get build plan params
func (o *GetBuildPlanParams) SetComponentCanonical(componentCanonical string) {
	o.ComponentCanonical = componentCanonical
}

// WithEnvironmentCanonical adds the environmentCanonical to the get build plan params
func (o *GetBuildPlanParams) WithEnvironmentCanonical(environmentCanonical string) *GetBuildPlanParams {
	o.SetEnvironmentCanonical(environmentCanonical)
	return o
}

// SetEnvironmentCanonical adds the environmentCanonical to the get build plan params
func (o *GetBuildPlanParams) SetEnvironmentCanonical(environmentCanonical string) {
	o.EnvironmentCanonical = environmentCanonical
}

// WithInpathPipelineName adds the inpathPipelineName to the get build plan params
func (o *GetBuildPlanParams) WithInpathPipelineName(inpathPipelineName string) *GetBuildPlanParams {
	o.SetInpathPipelineName(inpathPipelineName)
	return o
}

// SetInpathPipelineName adds the inpathPipelineName to the get build plan params
func (o *GetBuildPlanParams) SetInpathPipelineName(inpathPipelineName string) {
	o.InpathPipelineName = inpathPipelineName
}

// WithJobName adds the jobName to the get build plan params
func (o *GetBuildPlanParams) WithJobName(jobName string) *GetBuildPlanParams {
	o.SetJobName(jobName)
	return o
}

// SetJobName adds the jobName to the get build plan params
func (o *GetBuildPlanParams) SetJobName(jobName string) {
	o.JobName = jobName
}

// WithOrganizationCanonical adds the organizationCanonical to the get build plan params
func (o *GetBuildPlanParams) WithOrganizationCanonical(organizationCanonical string) *GetBuildPlanParams {
	o.SetOrganizationCanonical(organizationCanonical)
	return o
}

// SetOrganizationCanonical adds the organizationCanonical to the get build plan params
func (o *GetBuildPlanParams) SetOrganizationCanonical(organizationCanonical string) {
	o.OrganizationCanonical = organizationCanonical
}

// WithProjectCanonical adds the projectCanonical to the get build plan params
func (o *GetBuildPlanParams) WithProjectCanonical(projectCanonical string) *GetBuildPlanParams {
	o.SetProjectCanonical(projectCanonical)
	return o
}

// SetProjectCanonical adds the projectCanonical to the get build plan params
func (o *GetBuildPlanParams) SetProjectCanonical(projectCanonical string) {
	o.ProjectCanonical = projectCanonical
}

// WriteToRequest writes these params to a swagger request
func (o *GetBuildPlanParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param build_id
	if err := r.SetPathParam("build_id", o.BuildID); err != nil {
		return err
	}

	// path param component_canonical
	if err := r.SetPathParam("component_canonical", o.ComponentCanonical); err != nil {
		return err
	}

	// path param environment_canonical
	if err := r.SetPathParam("environment_canonical", o.EnvironmentCanonical); err != nil {
		return err
	}

	// path param inpath_pipeline_name
	if err := r.SetPathParam("inpath_pipeline_name", o.InpathPipelineName); err != nil {
		return err
	}

	// path param job_name
	if err := r.SetPathParam("job_name", o.JobName); err != nil {
		return err
	}

	// path param organization_canonical
	if err := r.SetPathParam("organization_canonical", o.OrganizationCanonical); err != nil {
		return err
	}

	// path param project_canonical
	if err := r.SetPathParam("project_canonical", o.ProjectCanonical); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
