// Code generated by go-swagger; DO NOT EDIT.

package organization_infrastructure_policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/cycloidio/cycloid-cli/client/models"
)

// CreateInfraPolicyReader is a Reader for the CreateInfraPolicy structure.
type CreateInfraPolicyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateInfraPolicyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateInfraPolicyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 411:
		result := NewCreateInfraPolicyLengthRequired()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewCreateInfraPolicyUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewCreateInfraPolicyDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateInfraPolicyOK creates a CreateInfraPolicyOK with default headers values
func NewCreateInfraPolicyOK() *CreateInfraPolicyOK {
	return &CreateInfraPolicyOK{}
}

/*CreateInfraPolicyOK handles this case with default header values.

The new InfraPolicy created.
*/
type CreateInfraPolicyOK struct {
	Payload *CreateInfraPolicyOKBody
}

func (o *CreateInfraPolicyOK) Error() string {
	return fmt.Sprintf("[POST /organizations/{organization_canonical}/infra_policies][%d] createInfraPolicyOK  %+v", 200, o.Payload)
}

func (o *CreateInfraPolicyOK) GetPayload() *CreateInfraPolicyOKBody {
	return o.Payload
}

func (o *CreateInfraPolicyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(CreateInfraPolicyOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateInfraPolicyLengthRequired creates a CreateInfraPolicyLengthRequired with default headers values
func NewCreateInfraPolicyLengthRequired() *CreateInfraPolicyLengthRequired {
	return &CreateInfraPolicyLengthRequired{}
}

/*CreateInfraPolicyLengthRequired handles this case with default header values.

The request has a body but it doesn't have a Content-Length header.
*/
type CreateInfraPolicyLengthRequired struct {
}

func (o *CreateInfraPolicyLengthRequired) Error() string {
	return fmt.Sprintf("[POST /organizations/{organization_canonical}/infra_policies][%d] createInfraPolicyLengthRequired ", 411)
}

func (o *CreateInfraPolicyLengthRequired) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateInfraPolicyUnprocessableEntity creates a CreateInfraPolicyUnprocessableEntity with default headers values
func NewCreateInfraPolicyUnprocessableEntity() *CreateInfraPolicyUnprocessableEntity {
	return &CreateInfraPolicyUnprocessableEntity{}
}

/*CreateInfraPolicyUnprocessableEntity handles this case with default header values.

All the custom errors that are generated from the Cycloid API
*/
type CreateInfraPolicyUnprocessableEntity struct {
	Payload *models.ErrorPayload
}

func (o *CreateInfraPolicyUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /organizations/{organization_canonical}/infra_policies][%d] createInfraPolicyUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *CreateInfraPolicyUnprocessableEntity) GetPayload() *models.ErrorPayload {
	return o.Payload
}

func (o *CreateInfraPolicyUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorPayload)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateInfraPolicyDefault creates a CreateInfraPolicyDefault with default headers values
func NewCreateInfraPolicyDefault(code int) *CreateInfraPolicyDefault {
	return &CreateInfraPolicyDefault{
		_statusCode: code,
	}
}

/*CreateInfraPolicyDefault handles this case with default header values.

The response sent when an unexpected error happened, as known as an internal server error.
*/
type CreateInfraPolicyDefault struct {
	_statusCode int

	Payload *models.ErrorPayload
}

// Code gets the status code for the create infra policy default response
func (o *CreateInfraPolicyDefault) Code() int {
	return o._statusCode
}

func (o *CreateInfraPolicyDefault) Error() string {
	return fmt.Sprintf("[POST /organizations/{organization_canonical}/infra_policies][%d] createInfraPolicy default  %+v", o._statusCode, o.Payload)
}

func (o *CreateInfraPolicyDefault) GetPayload() *models.ErrorPayload {
	return o.Payload
}

func (o *CreateInfraPolicyDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorPayload)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*CreateInfraPolicyOKBody create infra policy o k body
swagger:model CreateInfraPolicyOKBody
*/
type CreateInfraPolicyOKBody struct {

	// data
	// Required: true
	Data *models.InfraPolicy `json:"data"`
}

// Validate validates this create infra policy o k body
func (o *CreateInfraPolicyOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreateInfraPolicyOKBody) validateData(formats strfmt.Registry) error {

	if err := validate.Required("createInfraPolicyOK"+"."+"data", "body", o.Data); err != nil {
		return err
	}

	if o.Data != nil {
		if err := o.Data.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("createInfraPolicyOK" + "." + "data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *CreateInfraPolicyOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateInfraPolicyOKBody) UnmarshalBinary(b []byte) error {
	var res CreateInfraPolicyOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
